import type { Theme } from '@skeletonlabs/skeleton/themes'

export const felderaModern = {
  name: 'feldera-modern-theme',
  properties: {
    '--space-scale-factor': '1',
    '--type-scale-factor': '1.0',
    '--type-scale-1': 'calc(0.75rem * var(--type-scale-factor))',
    '--type-scale-2': 'calc(0.875rem * var(--type-scale-factor))',
    '--type-scale-3': 'calc(1rem * var(--type-scale-factor))',
    '--type-scale-4': 'calc(1.125rem * var(--type-scale-factor))',
    '--type-scale-5': 'calc(1.25rem * var(--type-scale-factor))',
    '--type-scale-6': 'calc(1.5rem * var(--type-scale-factor))',
    '--type-scale-7': 'calc(1.875rem * var(--type-scale-factor))',
    '--type-scale-8': 'calc(2.25rem * var(--type-scale-factor))',
    '--type-scale-9': 'calc(3rem * var(--type-scale-factor))',
    '--type-scale-10': 'calc(3.75rem * var(--type-scale-factor))',
    '--type-scale-11': 'calc(4.5rem * var(--type-scale-factor))',
    '--type-scale-12': 'calc(6rem * var(--type-scale-factor))',
    '--type-scale-13': 'calc(8rem * var(--type-scale-factor))',
    '--base-font-color': 'var(--color-surface-950)',
    '--base-font-color-dark': 'var(--color-surface-50)',
    '--base-font-family': 'DM Sans Variable',
    '--base-font-size': 'inherit',
    '--base-line-height': 'inherit',
    '--base-font-weight': 'normal',
    '--base-font-style': 'normal',
    '--base-letter-spacing': '0em',
    '--heading-font-color': 'var(--color-surface-950)',
    '--heading-font-color-dark': 'var(--color-surface-50)',
    '--heading-font-family': 'inherit',
    '--heading-font-weight': 'bold',
    '--heading-font-style': 'normal',
    '--heading-letter-spacing': 'inherit',
    '--anchor-font-color': 'var(--color-primary-500)',
    '--anchor-font-color-dark': 'var(--color-primary-500)',
    '--anchor-font-family': 'inherit',
    '--anchor-font-size': 'inherit',
    '--anchor-line-height': 'inherit',
    '--anchor-font-weight': 'normal',
    '--anchor-font-style': 'normal',
    '--anchor-letter-spacing': 'inherit',
    '--anchor-text-decoration': 'none',
    '--anchor-text-decoration-hover': 'underline',
    '--anchor-text-decoration-active': 'none',
    '--anchor-text-decoration-focus': 'none',
    '--body-background-color': 'var(--color-surface-50)',
    '--body-background-color-dark': 'var(--color-surface-950)',
    '--radii-default': '6px',
    '--radii-container': '12px',
    '--border-width-default': '1px',
    '--ring-width-default': '1px',
    '--outline-width-default': '1px',
    '--divide-width-default': '1px',
    '--color-primary-50': '243 214 241',
    '--color-primary-100': '234 181 230',
    '--color-primary-200': '225 149 219',
    '--color-primary-300': '215 116 207',
    '--color-primary-400': '206 84 196',
    '--color-primary-500': '197 51 185',
    '--color-primary-600': '165 43 155',
    '--color-primary-700': '134 35 126',
    '--color-primary-800': '102 27 96',
    '--color-primary-900': '71 19 67',
    '--color-primary-950': '39 11 37',
    '--color-primary-contrast-dark': 'var(--color-primary-950)',
    '--color-primary-contrast-light': 'var(--color-surface-50)',
    '--color-primary-contrast-50': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-100': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-200': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-300': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-400': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-500': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-600': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-700': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-800': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-900': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-950': 'var(--color-primary-contrast-light)',
    '--color-secondary-50': '255 249 237',
    '--color-secondary-100': '254 234 205',
    '--color-secondary-200': '254 219 174',
    '--color-secondary-300': '253 205 142',
    '--color-secondary-400': '253 190 111',
    '--color-secondary-500': '252 175 79',
    '--color-secondary-600': '215 145 65',
    '--color-secondary-700': '178 115 51',
    '--color-secondary-800': '141 86 36',
    '--color-secondary-900': '104 56 22',
    '--color-secondary-950': '67 26 8',
    '--color-secondary-contrast-dark': 'var(--color-secondary-950)',
    '--color-secondary-contrast-light': 'var(--color-secondary-50)',
    '--color-secondary-contrast-50': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-100': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-200': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-300': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-400': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-500': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-600': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-700': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-800': 'var(--color-secondary-contrast-light)',
    '--color-secondary-contrast-900': 'var(--color-secondary-contrast-light)',
    '--color-secondary-contrast-950': 'var(--color-secondary-contrast-light)',
    '--color-tertiary-50': '242 249 249',
    '--color-tertiary-100': '218 232 219',
    '--color-tertiary-200': '194 215 189',
    '--color-tertiary-300': '169 199 160',
    '--color-tertiary-400': '145 182 130',
    '--color-tertiary-500': '121 165 100',
    '--color-tertiary-600': '102 141 90',
    '--color-tertiary-700': '83 117 80',
    '--color-tertiary-800': '64 92 70',
    '--color-tertiary-900': '45 68 60',
    '--color-tertiary-950': '26 44 50',
    '--color-tertiary-contrast-dark': 'var(--color-tertiary-950)',
    '--color-tertiary-contrast-light': 'var(--color-tertiary-50)',
    '--color-tertiary-contrast-50': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-100': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-200': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-300': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-400': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-500': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-600': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-700': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-800': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-900': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-950': 'var(--color-tertiary-contrast-light)',
    '--color-success-50': '204 255 158',
    '--color-success-100': '177 240 132',
    '--color-success-200': '150 225 106',
    '--color-success-300': '123 210 81',
    '--color-success-400': '96 195 55',
    '--color-success-500': '69 180 29',
    '--color-success-600': '55 156 23',
    '--color-success-700': '41 133 17',
    '--color-success-800': '28 109 12',
    '--color-success-900': '14 86 6',
    '--color-success-950': '0 62 0',
    '--color-success-contrast-dark': 'var(--color-success-950)',
    '--color-success-contrast-light': 'var(--color-success-50)',
    '--color-success-contrast-50': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-100': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-200': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-300': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-400': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-500': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-600': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-700': 'var(--color-success-contrast-light)',
    '--color-success-contrast-800': 'var(--color-success-contrast-light)',
    '--color-success-contrast-900': 'var(--color-success-contrast-light)',
    '--color-success-contrast-950': 'var(--color-success-contrast-light)',
    '--color-warning-50': '255 255 165',
    '--color-warning-100': '245 241 139',
    '--color-warning-200': '235 226 113',
    '--color-warning-300': '226 212 86',
    '--color-warning-400': '216 197 60',
    '--color-warning-500': '206 183 34',
    '--color-warning-600': '181 160 27',
    '--color-warning-700': '156 138 20',
    '--color-warning-800': '131 115 14',
    '--color-warning-900': '106 93 7',
    '--color-warning-950': '81 70 0',
    '--color-warning-contrast-dark': 'var(--color-surface-950)',
    '--color-warning-contrast-light': 'var(--color-surface-50)',
    '--color-warning-contrast-50': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-100': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-200': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-300': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-400': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-500': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-600': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-700': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-800': 'var(--color-warning-contrast-light)',
    '--color-warning-contrast-900': 'var(--color-warning-contrast-light)',
    '--color-warning-contrast-950': 'var(--color-warning-contrast-light)',
    '--color-error-50': '255 199 216',
    '--color-error-100': '251 159 182',
    '--color-error-200': '247 119 148',
    '--color-error-300': '243 80 115',
    '--color-error-400': '239 40 81',
    '--color-error-500': '235 0 47',
    '--color-error-600': '203 0 38',
    '--color-error-700': '172 0 29',
    '--color-error-800': '140 0 20',
    '--color-error-900': '109 0 11',
    '--color-error-950': '77 0 2',
    '--color-error-contrast-dark': 'var(--color-surface-900)',
    '--color-error-contrast-light': 'var(--color-surface-50)',
    '--color-error-contrast-50': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-100': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-200': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-300': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-400': 'var(--color-error-contrast-light)',
    '--color-error-contrast-500': 'var(--color-error-contrast-light)',
    '--color-error-contrast-600': 'var(--color-error-contrast-light)',
    '--color-error-contrast-700': 'var(--color-error-contrast-light)',
    '--color-error-contrast-800': 'var(--color-error-contrast-light)',
    '--color-error-contrast-900': 'var(--color-error-contrast-light)',
    '--color-error-contrast-950': 'var(--color-error-contrast-light)',
    '--color-surface-50': '242 242 242',
    '--color-surface-100': '216 216 216',
    '--color-surface-200': '190 190 190',
    '--color-surface-300': '165 165 165',
    '--color-surface-400': '139 139 139',
    '--color-surface-500': '113 113 113',
    '--color-surface-600': '98 98 98',
    '--color-surface-700': '83 83 83',
    '--color-surface-800': '68 68 68',
    '--color-surface-900': '53 53 53',
    '--color-surface-950': '33 33 33',
    '--color-surface-contrast-dark': 'var(--color-surface-950)',
    '--color-surface-contrast-light': 'var(--color-surface-50)',
    '--color-surface-contrast-50': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-100': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-200': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-300': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-400': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-500': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-600': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-700': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-800': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-900': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-950': 'var(--color-surface-contrast-light)'
  },
  metadata: {
    version: '3.0.0'
  }
} satisfies Theme
