import type { Theme } from '@skeletonlabs/skeleton/themes'

export const felderaModern = {
  name: 'feldera-modern-theme',
  properties: {
    '--type-scale-factor': '1',
    '--type-scale-1': 'calc(0.75rem * var(--type-scale-factor))',
    '--type-scale-2': 'calc(0.875rem * var(--type-scale-factor))',
    '--type-scale-3': 'calc(1rem * var(--type-scale-factor))',
    '--type-scale-4': 'calc(1.125rem * var(--type-scale-factor))',
    '--type-scale-5': 'calc(1.25rem * var(--type-scale-factor))',
    '--type-scale-6': 'calc(1.5rem * var(--type-scale-factor))',
    '--type-scale-7': 'calc(1.875rem * var(--type-scale-factor))',
    '--type-scale-8': 'calc(2.25rem * var(--type-scale-factor))',
    '--type-scale-9': 'calc(3rem * var(--type-scale-factor))',
    '--type-scale-10': 'calc(3.75rem * var(--type-scale-factor))',
    '--type-scale-11': 'calc(4.5rem * var(--type-scale-factor))',
    '--type-scale-12': 'calc(6rem * var(--type-scale-factor))',
    '--type-scale-13': 'calc(8rem * var(--type-scale-factor))',
    '--base-font-color': 'var(--color-surface-950)',
    '--base-font-color-dark': 'var(--color-surface-50)',
    '--base-font-family': 'DM Sans Variable',
    '--base-font-size': 'inherit',
    '--base-line-height': 'inherit',
    '--base-font-weight': 'normal',
    '--base-font-style': 'normal',
    '--base-letter-spacing': '0em',
    '--heading-font-color': 'inherit',
    '--heading-font-color-dark': 'inherit',
    '--heading-font-family': 'inherit',
    '--heading-font-weight': 'bold',
    '--heading-font-style': 'normal',
    '--heading-letter-spacing': 'inherit',
    '--anchor-font-color': 'var(--color-primary-500)',
    '--anchor-font-color-dark': 'var(--color-primary-500)',
    '--anchor-font-family': 'inherit',
    '--anchor-font-size': 'inherit',
    '--anchor-line-height': 'inherit',
    '--anchor-font-weight': 'inherit',
    '--anchor-font-style': 'inherit',
    '--anchor-letter-spacing': 'inherit',
    '--anchor-text-decoration': 'none',
    '--anchor-text-decoration-hover': 'underline',
    '--anchor-text-decoration-active': 'none',
    '--anchor-text-decoration-focus': 'none',
    '--space-scale-factor': '1',
    '--radii-default': '6px',
    '--radii-container': '6px',
    '--border-width-default': '1px',
    '--divide-width-default': '1px',
    '--outline-width-default': '1px',
    '--ring-width-default': '1px',
    '--body-background-color': 'var(--color-surface-50)',
    '--body-background-color-dark': 'var(--color-surface-950)',
    '--color-primary-50': '243 214 241',
    '--color-primary-100': '234 181 230',
    '--color-primary-200': '225 149 219',
    '--color-primary-300': '215 116 207',
    '--color-primary-400': '206 84 196',
    '--color-primary-500': '197 51 185',
    '--color-primary-600': '172 44 161',
    '--color-primary-700': '147 38 138',
    '--color-primary-800': '121 31 114',
    '--color-primary-900': '96 25 91',
    '--color-primary-950': '71 18 67',
    '--color-primary-contrast-dark': 'var(--color-primary-950)',
    '--color-primary-contrast-light': 'var(--color-primary-50)',
    '--color-primary-contrast-50': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-100': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-200': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-300': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-400': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-500': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-600': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-700': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-800': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-900': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-950': 'var(--color-primary-contrast-light)',
    '--color-secondary-50': '232 232 232',
    '--color-secondary-100': '233 233 233',
    '--color-secondary-200': '234 234 234',
    '--color-secondary-300': '235 235 235',
    '--color-secondary-400': '236 236 236',
    '--color-secondary-500': '237 237 237',
    '--color-secondary-600': '197 197 197',
    '--color-secondary-700': '157 157 157',
    '--color-secondary-800': '118 118 118',
    '--color-secondary-900': '78 78 78',
    '--color-secondary-950': '38 38 38',
    '--color-secondary-contrast-dark': 'var(--color-secondary-950)',
    '--color-secondary-contrast-light': 'var(--color-secondary-50)',
    '--color-secondary-contrast-50': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-100': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-200': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-300': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-400': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-500': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-600': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-700': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-800': 'var(--color-secondary-contrast-light)',
    '--color-secondary-contrast-900': 'var(--color-secondary-contrast-light)',
    '--color-secondary-contrast-950': 'var(--color-secondary-contrast-light)',
    '--color-tertiary-50': '244 220 242',
    '--color-tertiary-100': '208 180 207',
    '--color-tertiary-200': '172 139 173',
    '--color-tertiary-300': '136 99 138',
    '--color-tertiary-400': '100 58 104',
    '--color-tertiary-500': '64 18 69',
    '--color-tertiary-600': '62 17 67',
    '--color-tertiary-700': '60 16 65',
    '--color-tertiary-800': '58 16 63',
    '--color-tertiary-900': '56 15 61',
    '--color-tertiary-950': '54 14 59',
    '--color-tertiary-contrast-dark': 'var(--color-tertiary-950)',
    '--color-tertiary-contrast-light': 'var(--color-tertiary-50)',
    '--color-tertiary-contrast-50': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-100': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-200': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-300': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-400': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-500': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-600': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-700': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-800': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-900': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-950': 'var(--color-tertiary-contrast-light)',
    '--color-success-50': '193 245 188',
    '--color-success-100': '158 233 150',
    '--color-success-200': '123 222 113',
    '--color-success-300': '88 210 75',
    '--color-success-400': '53 199 38',
    '--color-success-500': '18 187 0',
    '--color-success-600': '16 166 0',
    '--color-success-700': '14 145 0',
    '--color-success-800': '12 123 1',
    '--color-success-900': '10 102 1',
    '--color-success-950': '8 81 1',
    '--color-success-contrast-dark': 'var(--color-success-950)',
    '--color-success-contrast-light': 'var(--color-success-50)',
    '--color-success-contrast-50': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-100': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-200': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-300': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-400': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-500': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-600': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-700': 'var(--color-success-contrast-light)',
    '--color-success-contrast-800': 'var(--color-success-contrast-light)',
    '--color-success-contrast-900': 'var(--color-success-contrast-light)',
    '--color-success-contrast-950': 'var(--color-success-contrast-light)',
    '--color-warning-50': '252 216 144',
    '--color-warning-100': '252 208 121',
    '--color-warning-200': '252 200 97',
    '--color-warning-300': '251 192 74',
    '--color-warning-400': '251 184 50',
    '--color-warning-500': '251 176 27',
    '--color-warning-600': '212 148 24',
    '--color-warning-700': '173 120 20',
    '--color-warning-800': '135 92 17',
    '--color-warning-900': '96 64 13',
    '--color-warning-950': '57 36 10',
    '--color-warning-contrast-dark': 'var(--color-warning-950)',
    '--color-warning-contrast-light': 'var(--color-warning-50)',
    '--color-warning-contrast-50': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-100': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-200': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-300': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-400': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-500': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-600': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-700': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-800': 'var(--color-warning-contrast-light)',
    '--color-warning-contrast-900': 'var(--color-warning-contrast-light)',
    '--color-warning-contrast-950': 'var(--color-warning-contrast-light)',
    '--color-error-50': '253 211 214',
    '--color-error-100': '252 172 175',
    '--color-error-200': '251 133 135',
    '--color-error-300': '250 95 96',
    '--color-error-400': '249 56 56',
    '--color-error-500': '248 17 17',
    '--color-error-600': '228 14 14',
    '--color-error-700': '208 10 10',
    '--color-error-800': '188 7 7',
    '--color-error-900': '168 3 3',
    '--color-error-950': '148 0 0',
    '--color-error-contrast-dark': 'var(--color-error-950)',
    '--color-error-contrast-light': 'var(--color-error-50)',
    '--color-error-contrast-50': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-100': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-200': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-300': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-400': 'var(--color-error-contrast-light)',
    '--color-error-contrast-500': 'var(--color-error-contrast-light)',
    '--color-error-contrast-600': 'var(--color-error-contrast-light)',
    '--color-error-contrast-700': 'var(--color-error-contrast-light)',
    '--color-error-contrast-800': 'var(--color-error-contrast-light)',
    '--color-error-contrast-900': 'var(--color-error-contrast-light)',
    '--color-error-contrast-950': 'var(--color-error-contrast-light)',
    '--color-surface-50': '255 255 255',
    '--color-surface-100': '249 249 249',
    '--color-surface-200': '243 243 243',
    '--color-surface-300': '236 236 236',
    '--color-surface-400': '230 230 230',
    '--color-surface-500': '224 224 224',
    '--color-surface-600': '181 181 181',
    '--color-surface-700': '138 138 138',
    '--color-surface-800': '95 95 95',
    '--color-surface-900': '52 52 52',
    '--color-surface-950': '9 9 9',
    '--color-surface-contrast-dark': 'var(--color-surface-950)',
    '--color-surface-contrast-light': 'var(--color-surface-50)',
    '--color-surface-contrast-50': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-100': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-200': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-300': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-400': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-500': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-600': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-700': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-800': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-900': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-950': 'var(--color-surface-contrast-light)'
  },
  metadata: {
    version: '3.0.0'
  }
} satisfies Theme
