package org.dbsp.sqlCompiler.compiler.frontend;

import org.apache.calcite.sql.parser.SqlParserPos;

/** A SqlParserPos extended with additional information. */
// Perhaps some day we'll support multi-file projects, and then this should also contain the source file name.
public class ExtendedSqlParserPos extends SqlParserPos {
    /** If true the position is in a file internally generated by the compiler */
    public final boolean internal;

    public ExtendedSqlParserPos(SqlParserPos pos, boolean internal) {
        super(pos.getLineNum(), pos.getColumnNum(), pos.getEndLineNum(), pos.getEndColumnNum());
        this.internal = internal;
    }
}
