package org.dbsp.sqlCompiler.compiler.backend.rust.multi;

import org.dbsp.sqlCompiler.circuit.DBSPCircuit;
import org.dbsp.sqlCompiler.circuit.DBSPDeclaration;
import org.dbsp.sqlCompiler.circuit.operator.DBSPOperator;
import org.dbsp.sqlCompiler.compiler.DBSPCompiler;
import org.dbsp.sqlCompiler.compiler.backend.rust.RustFileWriter;
import org.dbsp.sqlCompiler.compiler.backend.rust.RustWriter;
import org.dbsp.sqlCompiler.compiler.errors.CompilationError;
import org.dbsp.sqlCompiler.compiler.errors.UnimplementedException;
import org.dbsp.sqlCompiler.compiler.visitors.outer.CircuitVisitor;
import org.dbsp.sqlCompiler.ir.IDBSPInnerNode;
import org.dbsp.sqlCompiler.ir.IDBSPNode;
import org.dbsp.util.IIndentStream;
import org.dbsp.util.Utilities;

import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/** This class helps generate Rust code.
 * It is given a set of circuit and functions and generates code in multiple crates. */
public final class MultiCratesWriter extends RustWriter {
    public final String outputDirectory;
    public final List<CrateGenerator> generators;
    File rootDirectory;

    /** Create a writer which will generate code in the specified directory */
    public MultiCratesWriter(String outputDirectory, boolean preserve) throws IOException {
        this.outputDirectory = outputDirectory;
        this.generators = new ArrayList<>();
        this.rootDirectory = this.rootDirectory(preserve);
    }

    File rootDirectory(boolean preserve) {
        if (this.rootDirectory == null) {
            File file = new File(this.outputDirectory);
            if (!file.exists() || !file.isDirectory())
                throw new CompilationError("Output directory does not exist " +
                        Utilities.singleQuote(this.outputDirectory));
            if (!preserve)
                Utilities.deleteContents(file);
            this.rootDirectory = file;
        }
        return this.rootDirectory;
    }

    @Override
    public void setOutputStream(IIndentStream stream) {
        throw new UnimplementedException();
    }

    public void addCrate(CrateGenerator gen) {
        this.generators.add(gen);
    }

    public void write() throws IOException {
        File cargo = new File(this.rootDirectory, CrateGenerator.CARGO);
        PrintStream cargoStream = new PrintStream(Files.newOutputStream(cargo.toPath()));
        cargoStream.println("# Automatically generated by sql-to-dbsp");
        cargoStream.println("[workspace]");
        cargoStream.println("members = [");
        boolean first = true;
        for (CrateGenerator gen: this.generators) {
            if (!first)
                cargoStream.println(",");
            first = false;
            cargoStream.print("   " + Utilities.doubleQuote(gen.crateName));
        }
        cargoStream.println();
        cargoStream.println("]");

        cargoStream.println("""
                [patch.crates-io]
                datafusion = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }
                datafusion-common = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }
                datafusion-expr = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }
                datafusion-functions = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }
                datafusion-functions-aggregate = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }
                datafusion-physical-expr = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }
                datafusion-physical-plan = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }
                datafusion-proto = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }
                datafusion-sql = { git = "https://github.com/ryzhyk/datafusion.git", rev = "f561db7" }""");

        cargoStream.close();
    }

    @Override
    public void write(DBSPCompiler compiler) throws IOException {
        StructuresUsed used = this.analyze(compiler);

        CircuitWriter mainWriter = new CircuitWriter();
        RustFileWriter globalsWriter = new RustFileWriter().withUdf(true).withMalloc(false);
        // Main crate contains the circuit
        CrateGenerator main = new CrateGenerator(this.rootDirectory, "main", mainWriter);
        // Crate with global variables
        CrateGenerator globals = new CrateGenerator(this.rootDirectory, "globals", globalsWriter);
        this.addCrate(main);
        this.addCrate(globals);

        // One crate for each tuple size used
        Map<Integer, CrateGenerator> tupleCrates = new HashMap<>();
        for (int i: used.tupleSizesUsed) {
            if (i < StructuresUsed.PREDEFINED) continue;
            StructuresUsed t = new StructuresUsed();
            t.tupleSizesUsed.add(i);
            RustFileWriter tWriter = new RustFileWriter().withUdf(false).withMalloc(false);
            tWriter.setUsed(t);
            CrateGenerator tuple = new CrateGenerator(this.rootDirectory, "tuple" + i, tWriter);
            Utilities.putNew(tupleCrates, i, tuple);
            tuple.write(compiler);
            this.addCrate(tuple);
        }

        // One crate for each semigroup size used
        Map<Integer, CrateGenerator> semiCrates = new HashMap<>();
        for (int i: used.semigroupSizesUsed) {
            StructuresUsed t = new StructuresUsed();
            t.semigroupSizesUsed.add(i);
            RustFileWriter tWriter = new RustFileWriter().withUdf(false).withMalloc(false);
            tWriter.setUsed(t);
            CrateGenerator semi = new CrateGenerator(this.rootDirectory, "semi" + i, tWriter);
            Utilities.putNew(semiCrates, i, semi);
            semi.write(compiler);
            this.addCrate(semi);
        }

        for (IDBSPNode node: this.toWrite) {
            if (node.is(IDBSPInnerNode.class))
                globals.add(node);
            else {
                DBSPCircuit circuit = node.to(DBSPCircuit.class);
                main.add(node);
                // Move all declarations to the globals crate as inner nodes
                for (DBSPDeclaration decl: circuit.declarations)
                    globals.add(decl.item);
                circuit.declarationMap.clear();
                circuit.declarations.clear();
                for (DBSPOperator operator: circuit.allOperators) {
                    String name = operator.getNodeName(USE_HASH_NAMES);
                    // One crate per operator
                    SingleOperatorWriter single = new SingleOperatorWriter(operator, circuit, true);
                    StructuresUsed locallyUsed = new StructuresUsed();
                    FindResources finder = new FindResources(compiler, locallyUsed);
                    CircuitVisitor circuitFinder = finder.getCircuitVisitor(false);
                    operator.accept(circuitFinder);
                    for (var input: operator.inputs) {
                        input.outputType().accept(finder);
                    }
                    CrateGenerator op = new CrateGenerator(this.rootDirectory, name, single);
                    op.addDependency(globals);
                    for (int i: locallyUsed.tupleSizesUsed) {
                        if (i < StructuresUsed.PREDEFINED) continue;
                        CrateGenerator gen = Utilities.getExists(tupleCrates, i);
                        op.addDependency(gen);
                    }
                    for (int i: locallyUsed.semigroupSizesUsed) {
                        CrateGenerator gen = Utilities.getExists(semiCrates, i);
                        op.addDependency(gen);
                    }
                    main.addDependency(op);
                    op.write(compiler);
                    this.addCrate(op);
                }
            }
        }
        globals.write(compiler);
        File file = new File(new File(new File(globals.baseDirectory, globals.crateName), "src"), DBSPCompiler.UDF_FILE_NAME);
        if (!file.exists())
            Utilities.createEmptyFile(file.toPath());
        main.write(compiler);
        this.write();
    }
}
