[package]
name = "pipeline-manager"
version = "0.18.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Data pipeline manager for the Feldera continuous analytics platform."
homepage = "https://github.com/feldera/feldera"
repository = "https://github.com/feldera/feldera"
keywords = ["DBSP", "streaming", "analytics", "database", "webui"]
categories = ["database", "gui"]
publish = false

[package.metadata.cargo-udeps.ignore]
development = ["pg-client-config"]

[dependencies]
pipeline_types = { path = "../pipeline-types/" }
actix-web = "4.3"
actix-web-static-files = "4.0.0"
actix-files = "0.6.2"
awc = {version = "3.1.0", features = ["openssl"] } # Needed for auth workflows
static-files = "0.2.3"
actix-cors = "0.6.4"
anyhow = { version = "1.0.57", features = ["backtrace"] }
tokio = { version = "1.25.0", features = ["rt-multi-thread", "fs", "macros", "process", "io-util", "io-std", "signal"] }
log = "0.4.20"
env_logger = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.103"
serde_yaml = "0.9.14"
clap = { version = "4.0.32", features = ["derive"] }
utoipa = { version = "4.1", features = ["actix_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "4", features = ["actix-web"] }
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde"] }
tempfile = { version = "3" }
futures-util = "0.3.28"
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-uuid-1"]}
async-trait = "0.1"
colored = "2.0.0"
deadpool-postgres = "0.10.5"
jsonwebtoken = "8"
actix-web-httpauth = "0.8.0"
cached = { version="0.43.0", features = ["async"]}
# Waiting for https://github.com/faokunega/pg-embed/pull/26
pg-embed = { git = "https://github.com/gz/pg-embed.git", rev = "8906af8", optional = true, default-features = false, features = ["rt_tokio"] }
rand = "0.8.5"
openssl = "0.10.55"
static_assertions = "1.1.0"
uuid = { version = "1.6.1", features = ["v7", "std", "serde"] }
refinery = {version = "0.8.10", features = ["tokio-postgres"]}
reqwest = {version = "0.11.18", features = ["json"]}
url = {version = "2.4.0"}
dirs = "5.0"
prometheus-client = "0.22.0"
once_cell = "1.18.0"
rdkafka = { version = "0.34.0", features = ["cmake-build", "ssl-vendored", "gssapi-vendored"] }
thiserror = "1.0"

[features]
integration-test = []

[build-dependencies]
change-detection = "1.2"
static-files = "0.2.3"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
pretty_assertions = "1.3.0"
pg-client-config = "0.1.2"
base64 = "0.21.0"
actix-http = "3.3.1"
serial_test = "2.0.0"
aws-sdk-cognitoidentityprovider = "0.28.0"
aws-config = "0.55.3"
wiremock = "0.5"
pipeline_types = { path = "../pipeline-types/", features = ["testing"] }

# Used in integration tests
[dev-dependencies.tokio]
version = "*"
features = ["sync"]

[package.metadata.cargo-machete]
ignored = ["static-files"]
