[tasks.build]
args = ["build", "--release"]

[tasks.openapi_json]
description = "Dump OpenAPI specification of the REST API to 'openapi.json'"
dependencies = ["build"]
command = "cargo"
args = ["run", "--release",  "--", "--dump-openapi"]

[tasks.openapi_python]
description = "Generate Python bindings for the REST API"
dependencies = ["openapi_json"]
script = '''
pip3 install openapi-python-client
cd ../../python
rm -rf dbsp-api-client
openapi-python-client generate --path ../crates/pipeline_manager/openapi.json
pip3 install ./dbsp-api-client
pip3 install .
'''

[tasks.python_test]
description = "Test Python API"
dependencies = ["openapi_python"]
script = '''
../../scripts/start_manager.sh $(python3 -c 'import tempfile; print(tempfile.gettempdir(), end="")')/pipeline_data
python3 ../../python/test.py
'''
