[package]
name = "webui-tester"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Tester for Web UI for the Feldera continuous analytics platform"
homepage = "https://github.com/feldera/feldera"
repository = "https://github.com/feldera/feldera"
keywords = ["DBSP", "streaming", "analytics", "database", "test"]
publish = false

[dev-dependencies]
thirtyfour = "0.32.0-rc.7"
tokio = "1.28"
anyhow = "1.0"
log = "0.4"
