import type { Theme } from '@skeletonlabs/skeleton/plugin'

export const felderaTheme = {
  name: 'feldera-theme',
  properties: {
    '--space-scale-factor': '1',
    '--type-scale-factor': '1.0',
    '--type-scale-1': 'calc(0.75rem * var(--type-scale-factor))',
    '--type-scale-2': 'calc(0.875rem * var(--type-scale-factor))',
    '--type-scale-3': 'calc(1rem * var(--type-scale-factor))',
    '--type-scale-4': 'calc(1.125rem * var(--type-scale-factor))',
    '--type-scale-5': 'calc(1.25rem * var(--type-scale-factor))',
    '--type-scale-6': 'calc(1.5rem * var(--type-scale-factor))',
    '--type-scale-7': 'calc(1.875rem * var(--type-scale-factor))',
    '--type-scale-8': 'calc(2.25rem * var(--type-scale-factor))',
    '--type-scale-9': 'calc(3rem * var(--type-scale-factor))',
    '--type-scale-10': 'calc(3.75rem * var(--type-scale-factor))',
    '--type-scale-11': 'calc(4.5rem * var(--type-scale-factor))',
    '--type-scale-12': 'calc(6rem * var(--type-scale-factor))',
    '--type-scale-13': 'calc(8rem * var(--type-scale-factor))',
    '--base-font-color': 'var(--color-surface-950)',
    '--base-font-color-dark': 'var(--color-surface-50)',
    '--base-font-family': 'system-ui, sans-serif',
    '--base-font-size': 'inherit',
    '--base-line-height': 'inherit',
    '--base-font-weight': 'normal',
    '--base-font-style': 'normal',
    '--base-letter-spacing': '0em',
    '--heading-font-color': 'var(--color-surface-950)',
    '--heading-font-color-dark': 'var(--color-surface-50)',
    '--heading-font-family': 'inherit',
    '--heading-font-weight': 'bold',
    '--heading-font-style': 'normal',
    '--heading-letter-spacing': 'inherit',
    '--anchor-font-color': '0 0 0',
    '--anchor-font-color-dark': '255 255 255',
    '--anchor-font-family': 'inherit',
    '--anchor-font-size': 'inherit',
    '--anchor-line-height': 'inherit',
    '--anchor-font-weight': 'normal',
    '--anchor-font-style': 'normal',
    '--anchor-letter-spacing': 'inherit',
    '--anchor-text-decoration': 'none',
    '--anchor-text-decoration-hover': 'underline',
    '--anchor-text-decoration-active': 'none',
    '--anchor-text-decoration-focus': 'none',
    '--body-background-color': 'var(--color-surface-50)',
    '--body-background-color-dark': 'var(--color-surface-950)',
    '--radii-default': '6px',
    '--radii-container': '6px',
    '--border-width-default': '1px',
    '--ring-width-default': '1px',
    '--outline-width-default': '1px',
    '--divide-width-default': '1px',
    '--color-primary-50': '244 229 255',
    '--color-primary-100': '216 205 255',
    '--color-primary-200': '188 181 255',
    '--color-primary-300': '161 156 255',
    '--color-primary-400': '133 132 255',
    '--color-primary-500': '105 108 255',
    '--color-primary-600': '84 88 230',
    '--color-primary-700': '63 69 205',
    '--color-primary-800': '42 49 179',
    '--color-primary-900': '21 30 154',
    '--color-primary-950': '0 10 129',
    '--color-primary-contrast-dark': 'var(--color-primary-950)',
    '--color-primary-contrast-light': 'var(--color-primary-50)',
    '--color-primary-contrast-50': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-100': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-200': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-300': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-400': 'var(--color-primary-contrast-dark)',
    '--color-primary-contrast-500': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-600': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-700': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-800': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-900': 'var(--color-primary-contrast-light)',
    '--color-primary-contrast-950': 'var(--color-primary-contrast-light)',
    '--color-secondary-50': '255 255 255',
    '--color-secondary-100': '231 233 237',
    '--color-secondary-200': '206 211 218',
    '--color-secondary-300': '182 190 200',
    '--color-secondary-400': '157 168 181',
    '--color-secondary-500': '133 146 163',
    '--color-secondary-600': '112 125 141',
    '--color-secondary-700': '90 103 119',
    '--color-secondary-800': '69 82 96',
    '--color-secondary-900': '47 60 74',
    '--color-secondary-950': '26 39 52',
    '--color-secondary-contrast-dark': 'var(--color-secondary-950)',
    '--color-secondary-contrast-light': 'var(--color-secondary-50)',
    '--color-secondary-contrast-50': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-100': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-200': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-300': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-400': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-500': 'var(--color-secondary-contrast-dark)',
    '--color-secondary-contrast-600': 'var(--color-secondary-contrast-light)',
    '--color-secondary-contrast-700': 'var(--color-secondary-contrast-light)',
    '--color-secondary-contrast-800': 'var(--color-secondary-contrast-light)',
    '--color-secondary-contrast-900': 'var(--color-secondary-contrast-light)',
    '--color-secondary-contrast-950': 'var(--color-secondary-contrast-light)',
    '--color-tertiary-50': '193 255 255',
    '--color-tertiary-100': '155 243 251',
    '--color-tertiary-200': '117 231 247',
    '--color-tertiary-300': '79 219 244',
    '--color-tertiary-400': '41 207 240',
    '--color-tertiary-500': '3 195 236',
    '--color-tertiary-600': '2 172 212',
    '--color-tertiary-700': '2 148 187',
    '--color-tertiary-800': '1 125 163',
    '--color-tertiary-900': '1 101 138',
    '--color-tertiary-950': '0 78 114',
    '--color-tertiary-contrast-dark': 'var(--color-tertiary-950)',
    '--color-tertiary-contrast-light': 'var(--color-tertiary-50)',
    '--color-tertiary-contrast-50': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-100': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-200': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-300': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-400': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-500': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-600': 'var(--color-tertiary-contrast-dark)',
    '--color-tertiary-contrast-700': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-800': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-900': 'var(--color-tertiary-contrast-light)',
    '--color-tertiary-contrast-950': 'var(--color-tertiary-contrast-light)',
    '--color-success-50': '248 255 184',
    '--color-success-100': '221 248 158',
    '--color-success-200': '194 241 132',
    '--color-success-300': '167 235 107',
    '--color-success-400': '140 228 81',
    '--color-success-500': '113 221 55',
    '--color-success-600': '90 197 44',
    '--color-success-700': '68 172 33',
    '--color-success-800': '45 148 22',
    '--color-success-900': '23 123 11',
    '--color-success-950': '0 99 0',
    '--color-success-contrast-dark': 'var(--color-success-950)',
    '--color-success-contrast-light': 'var(--color-success-50)',
    '--color-success-contrast-50': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-100': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-200': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-300': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-400': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-500': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-600': 'var(--color-success-contrast-dark)',
    '--color-success-contrast-700': 'var(--color-success-contrast-light)',
    '--color-success-contrast-800': 'var(--color-success-contrast-light)',
    '--color-success-contrast-900': 'var(--color-success-contrast-light)',
    '--color-success-contrast-950': 'var(--color-success-contrast-light)',
    '--color-warning-50': '255 255 152',
    '--color-warning-100': '255 238 122',
    '--color-warning-200': '255 221 91',
    '--color-warning-300': '255 205 61',
    '--color-warning-400': '255 188 30',
    '--color-warning-500': '255 171 0',
    '--color-warning-600': '228 148 0',
    '--color-warning-700': '201 126 0',
    '--color-warning-800': '173 103 0',
    '--color-warning-900': '146 81 0',
    '--color-warning-950': '119 58 0',
    '--color-warning-contrast-dark': 'var(--color-warning-950)',
    '--color-warning-contrast-light': 'var(--color-warning-50)',
    '--color-warning-contrast-50': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-100': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-200': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-300': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-400': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-500': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-600': 'var(--color-warning-contrast-dark)',
    '--color-warning-contrast-700': 'var(--color-warning-contrast-light)',
    '--color-warning-contrast-800': 'var(--color-warning-contrast-light)',
    '--color-warning-contrast-900': 'var(--color-warning-contrast-light)',
    '--color-warning-contrast-950': 'var(--color-warning-contrast-light)',
    '--color-error-50': '255 230 230',
    '--color-error-100': '255 170 122',
    '--color-error-200': '255 143 99',
    '--color-error-300': '255 116 75',
    '--color-error-400': '255 89 52',
    '--color-error-500': '255 62 29',
    '--color-error-600': '226 50 23',
    '--color-error-700': '198 37 17',
    '--color-error-800': '169 25 12',
    '--color-error-900': '141 12 6',
    '--color-error-950': '112 0 0',
    '--color-error-contrast-dark': 'var(--color-error-950)',
    '--color-error-contrast-light': 'var(--color-error-50)',
    '--color-error-contrast-50': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-100': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-200': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-300': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-400': 'var(--color-error-contrast-dark)',
    '--color-error-contrast-500': 'var(--color-error-contrast-light)',
    '--color-error-contrast-600': 'var(--color-error-contrast-light)',
    '--color-error-contrast-700': 'var(--color-error-contrast-light)',
    '--color-error-contrast-800': 'var(--color-error-contrast-light)',
    '--color-error-contrast-900': 'var(--color-error-contrast-light)',
    '--color-error-contrast-950': 'var(--color-error-contrast-light)',
    '--color-surface-50': '245 245 249',
    '--color-surface-100': '230 229 234',
    '--color-surface-200': '205 205 213',
    '--color-surface-300': '181 180 192',
    '--color-surface-400': '156 156 171',
    '--color-surface-500': '131 131 150',
    '--color-surface-600': '110 110 128',
    '--color-surface-700': '89 89 107',
    '--color-surface-800': '68 69 85',
    '--color-surface-900': '47 48 64',
    '--color-surface-950': '26 27 42',
    '--color-surface-contrast-dark': 'var(--color-surface-950)',
    '--color-surface-contrast-light': 'var(--color-surface-50)',
    '--color-surface-contrast-50': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-100': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-200': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-300': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-400': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-500': 'var(--color-surface-contrast-dark)',
    '--color-surface-contrast-600': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-700': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-800': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-900': 'var(--color-surface-contrast-light)',
    '--color-surface-contrast-950': 'var(--color-surface-contrast-light)'
  }
} satisfies Theme
