{
 "title": "DBSP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "project_name", "query": { "query": "label_values(project_name)" } },
   {
    "name": "pipeline_id",
    "query": {
     "query": "label_values(input_total_bytes{project_name=~\"$project_name\"}, pipeline_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Input rate (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(input_total_bytes{pipeline_id=\"$pipeline_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input rate (records)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(input_total_records{pipeline_id=\"$pipeline_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output rate (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(output_transmitted_bytes{pipeline_id=\"$pipeline_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output rate (records)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(output_transmitted_records{pipeline_id=\"$pipeline_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "input_num_transport_errors{pipeline_id=\"$pipeline_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "input_num_parse_errors{pipeline_id=\"$pipeline_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "output_num_transport_errors{pipeline_id=\"$pipeline_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "output_num_encode_errors{pipeline_id=\"$pipeline_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input buffer size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "input_buffered_bytes{pipeline_id=\"$pipeline_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input buffer size (records)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "input_buffered_records{pipeline_id=\"$pipeline_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output buffer size (batches)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "output_buffered_batches{pipeline_id=\"$pipeline_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output  buffer size (records)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "output_buffered_records{pipeline_id=\"$pipeline_id\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}