[env]
RUST_BUILD_PROFILE = "--release"

[tasks.build]
command = "cargo"
args = ["build", "@@remove-empty(RUST_BUILD_PROFILE)"]

[tasks.openapi_json]
description = "Dump OpenAPI specification of the REST API to 'openapi.json'"
dependencies = ["build"]
cwd = "../../"
command = "cargo"
args = [
    "run",
    "--package",
    "pipeline-manager",
    "--bin",
    "pipeline-manager",
    "${RUST_BUILD_PROFILE}",
    "--",
    "--dump-openapi",
]

[tasks.start_manager]
script = '''
old_manager_pid=$(pgrep "pipeline-mana" || echo "")
echo "Old manager: " $old_manager_pid
if [ -n "$old_manager_pid" ]; then
    echo "Previous manager instance is running"
    exit 1
fi
../../scripts/start_manager.sh &
manager_pid=$!
while true; do
    if curl --output /dev/null --silent --head --fail http://localhost:8080; then
        echo "Pipeline manager is up and running"
        break
    else
        if ! ps -p $manager_pid > /dev/null; then
            echo "Manager process has terminated unexpectedly"
            exit 1
        fi
        sleep 1
    fi
done
'''
