//! Built-in connector descriptor manifest, baked in at platform build time.
//!
//! This crate exposes a single static JSON string,
//! [`PLATFORM_MANIFEST_JSON`], produced by the crate's `build.rs` during
//! platform compilation.  The build script walks
//! [`feldera_adapterlib::connector::registered_connectors`] against the
//! built-in connector tree (`dbsp_adapters` + `feldera-datagen`) and
//! serializes the resulting [`feldera_adapterlib::connector::ConnectorManifestEntry`]
//! array.  `pipeline-manager` parses the string at startup — no subprocess,
//! no Cargo invocation, no first-startup compile cost.
//!
//! The build-time approach is deliberately chosen over the alternatives:
//!
//! * Linking `dbsp_adapters` into `pipeline-manager` directly would inflate
//!   the orchestrator's compile time and binary size with the data-plane
//!   dependency tree (datafusion, deltalake, kafka, …) for no operational
//!   benefit.
//! * Spawning a describer subprocess at startup pushes the cost to first
//!   boot — minutes on cold sccache, observable to the operator.
//!
//! Putting the work in `[build-dependencies]` keeps the runtime binary
//! slim and shifts the cost onto `cargo build pipeline-manager` (where it
//! is amortized via sccache and the platform-build CI cache).

/// Built-in connector descriptor manifest, serialized as a JSON array of
/// [`feldera_adapterlib::connector::ConnectorManifestEntry`].
///
/// Generated by `build.rs` and embedded via `include_str!`.  Parse at
/// startup with `serde_json::from_str`.
pub const PLATFORM_MANIFEST_JSON: &str =
    include_str!(concat!(env!("OUT_DIR"), "/platform_manifest.json"));
