package org.dbsp.sqlCompiler.compiler.sql;

import org.dbsp.sqlCompiler.CompilerMain;
import org.dbsp.sqlCompiler.compiler.errors.CompilerMessages;
import org.dbsp.sqlCompiler.compiler.errors.UnsupportedException;
import org.dbsp.sqlCompiler.compiler.sql.tools.BaseSQLTests;
import org.dbsp.util.Utilities;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Compile the SQL programs in the feldera-qa repository, and rust-compile the results. */
public class QATests {
    // Some workload files have connectors generated by python scripts
    // Use a regex to replace them with an empty array
    // Ex:
    //     'connectors' = '{input_connectors}'
    // is replaced by
    //     'connectors' = '[]'
    // and
    //     ) WITH ('connectors' = '{orders1_connectors}');
    // is replaced by
    //     ) WITH ('connectors' = '[]');
    static File replaceConnectors(File source) throws IOException {
        Pattern p = Pattern.compile("^(.*)'connectors' = '\\{(.*)_connectors\\}'(.*)$");

        List<String> strings = Files.readAllLines(source.toPath());
        for (int i = 0; i < strings.size(); i++) {
            var s = strings.get(i);
            Matcher m = p.matcher(s);
            if (m.matches()) {
                final String repl = m.group(1) + "'connectors' = '[]'" + m.group(3);
                strings.set(i, repl);
            }
        }
        File file = BaseSQLTests.createInputScript(String.join("\n", strings));
        file.deleteOnExit();
        return file;
    }

    static void compileAndCheck(File file) throws SQLException, IOException {
        File input = replaceConnectors(file);
        CompilerMessages messages = CompilerMain.execute(
                "-i", "--alltables", "--ignoreOrder",
                "-o", BaseSQLTests.TEST_FILE_PATH, input.getAbsolutePath());
        if (messages.errorCount() > 0) {
            messages.print();
            throw new RuntimeException("Error during compilation");
        }
        Utilities.deleteFile(input, false);
        // BaseSQLTests.compileAndCheckRust(true);
    }

    /** Enumerate the SQL files in the QA repository.
     * The assumption is that this repository has been checked out in parallel with feldera. */
    static List<File> getQATests() {
        List<File> result = new ArrayList<>();
        String dir = "../../../feldera-qa";
        String[] subdirs = new String[] { "new/workloads", "." };
        for (var subdir : subdirs) {
            File file = new File(dir + "/" + subdir);
            if (file.exists()) {
                File[] directories = file.listFiles();
                if (directories == null)
                    return result;
                Arrays.sort(directories);
                for (File d : directories) {
                    File[] files = d.listFiles();
                    if (files == null)
                        continue;
                    for (File c : files) {
                        // The following eliminate some fda scripts
                        if (c.getName().contains("adhoc")) continue;
                        if (c.getName().matches("query.*view.sql")) continue;
                        if (c.getName().endsWith(".sql")) {
                            result.add(c);
                        }
                    }
                }
            }
        }
        return result;
    }

    @Test
    public void qaTests() throws SQLException {
        // BaseSQLTests.showPlan();
        for (File c : getQATests()) {
            // This program cannot be compiled because it contains a udf
            if (c.toString().matches(".*swiss.*-q1.*")) continue;
            // if (!c.toString().contains("x.sql")) continue;
            System.out.println("Compiling " + c);
            try {
                compileAndCheck(c);
            } catch (UnsupportedException | IOException ex) {
                // This is probably a file containing an ad-hoc query
                System.out.println(c.getName() + " skipped due to unsupported features.");
            }
        }
    }
}
