import type { PipelineStatus } from '$lib/services/pipelineManager'
import { P, match } from 'ts-pattern'

export const getPipelineStatusLabel = (status: PipelineStatus) => {
  return match(status)
    .with('Shutdown', { SqlWarning: P.any }, () => 'Ready To Start')
    .with('Starting up', () => 'Starting up')
    .with('Initializing', () => 'Initializing')
    .with('Paused', () => 'Paused')
    .with('Running', () => 'Running')
    .with('Pausing', () => 'Pausing')
    .with('Resuming', () => 'Resuming')
    .with('ShuttingDown', () => 'Shutting Down')
    .with({ PipelineError: P._ }, () => 'Pipeline Error')
    .with('Compiling SQL', () => 'Compiling SQL')
    .with('SQL compiled', () => 'SQL compiled')
    .with('Queued', () => 'Queued')
    .with('Compiling binary', () => 'Compiling Rust')
    .with('Unavailable', () => 'Unavailable')
    .with({ SqlError: P._ }, () => 'Program Error')
    .with({ RustError: P._ }, () => 'Program Error')
    .with({ SystemError: P._ }, () => 'Program Error')
    .exhaustive()
}

export const getDeploymentStatusLabel = (status: PipelineStatus) => {
  return match(status)
    .with('Shutdown', { SqlWarning: P.any }, () => '')
    .with('Starting up', () => 'Starting up')
    .with('Initializing', () => 'Initializing')
    .with('Paused', () => 'Paused')
    .with('Running', () => 'Running')
    .with('Pausing', () => 'Pausing')
    .with('Resuming', () => 'Resuming')
    .with('ShuttingDown', () => 'Shutting Down')
    .with({ PipelineError: P._ }, () => 'Pipeline Error')
    .with('Compiling SQL', () => '')
    .with('SQL compiled', () => '')
    .with('Queued', () => '')
    .with('Compiling binary', () => '')
    .with('Unavailable', () => 'Unavailable')
    .with({ SqlError: P._ }, () => '')
    .with({ RustError: P._ }, () => '')
    .with({ SystemError: P._ }, () => '')
    .exhaustive()
}

export const isPipelineIdle = (status: PipelineStatus) => {
  return match(status)
    .with('Shutdown', { SqlWarning: P.any }, () => true)
    .with('Starting up', () => false)
    .with('Initializing', () => false)
    .with('Paused', () => false)
    .with('Running', () => false)
    .with('Pausing', () => false)
    .with('Resuming', () => false)
    .with('ShuttingDown', () => false)
    .with({ PipelineError: P._ }, () => false)
    .with('Compiling SQL', () => true)
    .with('SQL compiled', () => true)
    .with('Queued', () => true)
    .with('Compiling binary', () => true)
    .with('Unavailable', () => false)
    .with({ SqlError: P._ }, () => true)
    .with({ RustError: P._ }, () => true)
    .with({ SystemError: P._ }, () => true)
    .exhaustive()
}

export const isMetricsAvailable = (status: PipelineStatus) => {
  return match(status)
    .with('Shutdown', { SqlWarning: P.any }, () => 'no' as const)
    .with('Starting up', () => 'no' as const)
    .with('Initializing', () => 'no' as const)
    .with('Paused', () => 'yes' as const)
    .with('Running', () => 'yes' as const)
    .with('Pausing', () => 'yes' as const)
    .with('Resuming', () => 'yes' as const)
    .with('ShuttingDown', () => 'no' as const)
    .with({ PipelineError: P._ }, () => 'no' as const)
    .with('Compiling SQL', () => 'no' as const)
    .with('SQL compiled', () => 'no' as const)
    .with('Queued', () => 'no' as const)
    .with('Compiling binary', () => 'no' as const)
    .with('Unavailable', () => 'soon' as const)
    .with({ SqlError: P._ }, () => 'no' as const)
    .with({ RustError: P._ }, () => 'no' as const)
    .with({ SystemError: P._ }, () => 'no' as const)
    .exhaustive()
}
