//! Benchmark comparing two transitive-closure computation approaches on acyclic
//! graphs similar to `examples/tutorial/tutorial10.rs`:
//!
//! - **recursive**: `Circuit::recursive`, which applies an implicit `distinct`
//!   on every nested clock tick. See [`build_recursive_variant`].
//! - **iterate**: `Circuit::iterate` with a manual feedback loop that only
//!   carries the per-iteration frontier and therefore skips the `distinct`.
//!   See [`build_iterate_variant`].
//! - **recursion**: `Circuit::recursion` (the `RecursionBuilder` API) with
//!   `without_distinct`.  It keeps the concise fixed-point form of the
//!   `recursive` variant, but — like the `iterate` variant — drops the
//!   `distinct` altogether, expressing declaratively what the `recursive`
//!   variant achieves with the `mark_distinct` trick.
//!   See [`build_recursion_variant`].
//!
//! The two variants are only semantically equivalent when there is at most one
//! path between any pair of nodes (see [`generate_forest`] for why), so the
//! benchmark drives random forests (and no general DAGs) and asserts the
//! variants agree before measuring.  In that regime the recursive variant's
//! `distinct` removes nothing yet still costs, so the iterate variant is
//! expected to win.  This mirrors `UNION` vs `UNION ALL` in recursive SQL CTEs.
//!
//! Run with, e.g.:
//! `cargo bench --bench transitive_closure_acyclic`

use criterion::{BatchSize, BenchmarkId, Criterion, Throughput, criterion_group, criterion_main};
use dbsp::{
    Circuit, CircuitBase, Consensus, DBSPHandle, NestedCircuit, NumEntries, OrdIndexedZSet,
    OutputHandle, Runtime, Stream, ZSetHandle, ZWeight,
    mimalloc::MiMalloc,
    operator::Z1,
    trace::BatchReaderFactories,
    typed_batch::SpineSnapshot,
    utils::{Tup2, Tup3, Tup4},
};
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;
use std::cell::Cell;

#[global_allocator]
static ALLOC: MiMalloc = MiMalloc;

type NodeId = u64;
type Weight = u64;
type CumWeight = u64;
type Hopcnt = u64;
type WeightedEdge = Tup3<NodeId, NodeId, Weight>;
type Path = Tup2<NodeId, NodeId>;
type TransClosurePath = Tup4<NodeId, NodeId, CumWeight, Hopcnt>;
type Accumulator = Stream<NestedCircuit, OrdIndexedZSet<Path, TransClosurePath>>;

struct TransClosureCircuit {
    handle: DBSPHandle,
    edges_input: ZSetHandle<WeightedEdge>,
    closure_output: OutputHandle<SpineSnapshot<OrdIndexedZSet<Path, TransClosurePath>>>,
}

/// Number of DBSP worker threads used for every circuit in this benchmark.
const WORKERS: usize = 4;

/// Deterministic seed so every run sees the same graphs.
const SEED: u64 = 0x0BADC0DE_DEADBEEF;

/// Largest edge weight generated by [`generate_forest`].
const MAX_EDGE_WEIGHT: Weight = 10;

/// A single-transaction workload: all edges of one acyclic graph.
type Workload = Vec<Tup2<WeightedEdge, ZWeight>>;

/// Generates a random weighted *forest* (each non-root node has exactly one
/// parent) as a single insertion batch.
///
/// Why a forest rather than an arbitrary DAG?  The two variants are only
/// semantically equivalent when there is **at most one path between any pair of
/// nodes**.  When several distinct paths connect the same `(start, end)` and
/// happen to share the same cumulative weight and hop count, the recursive
/// variant's `distinct` collapses them into a single tuple, whereas the iterate
/// variant (UNION ALL semantics) keeps the multiplicity, so the two disagree on
/// a general DAG.  A forest guarantees a unique path per reachable pair:
/// the `distinct` becomes pure overhead that removes nothing, and both variants
/// produce identical transitive closures.
///
/// Node `child` (for `child` in `1..nodes`) draws a uniformly random parent from
/// `0..child`, so edges always point from a lower id to a higher one and no cycle
/// can form.  Node `0` is the single root.  A bushy tree still exercises wide
/// fan-out joins because low-id nodes accumulate many children.
fn generate_forest(nodes: NodeId) -> Workload {
    let mut rng = ChaCha8Rng::seed_from_u64(SEED);
    let mut edges = Vec::with_capacity(nodes.saturating_sub(1) as usize);

    for child in 1..nodes {
        let parent = rng.gen_range(0..child);
        let weight = rng.gen_range(1..=MAX_EDGE_WEIGHT);
        edges.push(Tup2(Tup3(parent, child, weight), 1));
    }

    edges
}

/// Feeds a whole graph into a freshly built circuit in one transaction and
/// returns the number of paths in the resulting transitive closure.
///
/// The circuit (and its worker threads) is dropped on return, so the caller
/// must supply a fresh circuit for each measured iteration.
fn drive_once(mut circuit: TransClosureCircuit, mut workload: Workload) -> usize {
    circuit.edges_input.append(&mut workload);
    circuit
        .handle
        .transaction()
        .expect("transaction should succeed");
    circuit
        .closure_output
        .concat()
        .consolidate()
        .num_entries_shallow()
}

/// Cross-checks that both variants compute the same closure on the given graph,
/// returning the shared closure size (used both as a sanity check and to label
/// the benchmark with the output cardinality).
fn assert_variants_agree(workload: &Workload) -> usize {
    let recursive = build_recursive_variant().expect("build recursive circuit");
    let iterate = build_iterate_variant().expect("build iterate circuit");
    let recursion = build_recursion_variant().expect("build recursion circuit");

    let mut recursive_circuit = recursive.handle;
    let mut iterate_circuit = iterate.handle;
    let mut recursion_circuit = recursion.handle;

    recursive.edges_input.append(&mut workload.clone());
    iterate.edges_input.append(&mut workload.clone());
    recursion.edges_input.append(&mut workload.clone());
    recursive_circuit.transaction().unwrap();
    iterate_circuit.transaction().unwrap();
    recursion_circuit.transaction().unwrap();

    let recursive_closure = recursive.closure_output.concat().consolidate();
    let iterate_closure = iterate.closure_output.concat().consolidate();
    let recursion_closure = recursion.closure_output.concat().consolidate();

    assert_eq!(
        recursive_closure, iterate_closure,
        "recursive and iterate variants must agree on acyclic input"
    );
    assert_eq!(
        recursive_closure, recursion_closure,
        "recursive and recursion variants must agree on acyclic input"
    );

    recursive_closure.num_entries_shallow()
}

/// The forest sizes (in terms of node counts) we benchmark.
const GRAPH_SIZES: &[NodeId] = &[500, 1000, 2000];

fn transitive_closure_benches(c: &mut Criterion) {
    let mut group = c.benchmark_group("transitive-closure-acyclic");
    // Building a circuit spins up worker threads, so keep the sample count
    // modest to bound the wall-clock time of the whole benchmark.
    group.sample_size(25);

    for &nodes in GRAPH_SIZES {
        let workload = generate_forest(nodes);
        let closure_size = assert_variants_agree(&workload);
        let shape = format!("n{nodes}");
        println!(
            "graph {shape}: {} edges, closure of {closure_size} paths",
            workload.len()
        );

        // Report throughput in paths of the computed closure per second so the
        // two variants are compared on the same unit of useful work.
        group.throughput(Throughput::Elements(closure_size as u64));

        group.bench_with_input(
            BenchmarkId::new("recursive", &shape),
            &workload,
            |b, workload| {
                b.iter_batched(
                    || {
                        (
                            build_recursive_variant().expect("build recursive circuit"),
                            workload.clone(),
                        )
                    },
                    |(circuit, workload)| drive_once(circuit, workload),
                    BatchSize::PerIteration,
                );
            },
        );

        group.bench_with_input(
            BenchmarkId::new("iterate", &shape),
            &workload,
            |b, workload| {
                b.iter_batched(
                    || {
                        (
                            build_iterate_variant().expect("build iterate circuit"),
                            workload.clone(),
                        )
                    },
                    |(circuit, workload)| drive_once(circuit, workload),
                    BatchSize::PerIteration,
                );
            },
        );

        group.bench_with_input(
            BenchmarkId::new("recursion", &shape),
            &workload,
            |b, workload| {
                b.iter_batched(
                    || {
                        (
                            build_recursion_variant().expect("build recursion circuit"),
                            workload.clone(),
                        )
                    },
                    |(circuit, workload)| drive_once(circuit, workload),
                    BatchSize::PerIteration,
                );
            },
        );
    }

    group.finish();
}

criterion_group!(benches, transitive_closure_benches);
criterion_main!(benches);

/// Computes the transitive closure of an acyclic graph using DBSP's
/// [`recursive` API](dbsp::circuit::ChildCircuit::recursive).
fn build_recursive_variant() -> anyhow::Result<TransClosureCircuit> {
    let (handle, (edges_input, closure_output)) =
        Runtime::init_circuit(WORKERS, move |root_circuit| {
            let (edges, edges_input) = root_circuit.add_input_zset::<WeightedEdge>();

            let len_1 = edges.map_index(|Tup3(from, to, weight)| {
                (Tup2(*from, *to), Tup4(*from, *to, *weight, 1))
            });

            let closure = root_circuit.recursive(|child_circuit, closure: Accumulator| {
                let edges = edges.delta0(child_circuit);
                let len_1 = len_1.delta0(child_circuit);

                let closure = len_1
                    .plus(
                        &closure
                            .map_index(
                                |(Tup2(_start, _end), Tup4(start, end, cum_weight, hopcnt))| {
                                    (*end, Tup4(*start, *end, *cum_weight, *hopcnt))
                                },
                            )
                            .join_index(
                                &edges.map_index(|Tup3(from, to, weight)| {
                                    (*from, Tup3(*from, *to, *weight))
                                }),
                                |_end_from,
                                 Tup4(start, _end, cum_weight, hopcnt),
                                 Tup3(_from, to, weight)| {
                                    Some((
                                        Tup2(*start, *to),
                                        Tup4(*start, *to, cum_weight + weight, hopcnt + 1),
                                    ))
                                },
                            ),
                        //
                    )
                    // We explicitly mark the stream as distinct to avoid the
                    // unnecessary implicit distinct.
                    .mark_distinct();

                Ok(closure)
            })?;

            Ok((edges_input, closure.accumulate_output()))
        })?;

    Ok(TransClosureCircuit {
        handle,
        edges_input,
        closure_output,
    })
}

/// Computes the transitive closure of an acyclic graph using DBSP's
/// [`recursion` builder API](dbsp::circuit::ChildCircuit::recursion).
///
/// This is the same fixed-point computation as [`build_recursive_variant`], but
/// [`without_distinct`](dbsp::operator::RecursionBuilder::without_distinct)
/// drops the implicit `distinct` outright instead of neutralizing it with
/// `mark_distinct`.  On a forest that `distinct` removes nothing, so the result
/// is identical while the operator is gone entirely.
fn build_recursion_variant() -> anyhow::Result<TransClosureCircuit> {
    let (handle, (edges_input, closure_output)) =
        Runtime::init_circuit(WORKERS, move |root_circuit| {
            let (edges, edges_input) = root_circuit.add_input_zset::<WeightedEdge>();

            let len_1 = edges.map_index(|Tup3(from, to, weight)| {
                (Tup2(*from, *to), Tup4(*from, *to, *weight, 1))
            });

            let closure = root_circuit
                .recursion(
                    // A single recursive relation; its arity is inferred, so
                    // none is supplied.
                    |child_circuit| {
                        Ok(child_circuit.recursive_var::<OrdIndexedZSet<Path, TransClosurePath>>())
                    },
                    |child_circuit, closure: Accumulator| {
                        let edges = edges.delta0(child_circuit);
                        let len_1 = len_1.delta0(child_circuit);

                        Ok(len_1.plus(
                            &closure
                                .map_index(
                                    |(Tup2(_start, _end), Tup4(start, end, cum_weight, hopcnt))| {
                                        (*end, Tup4(*start, *end, *cum_weight, *hopcnt))
                                    },
                                )
                                .join_index(
                                    &edges.map_index(|Tup3(from, to, weight)| {
                                        (*from, Tup3(*from, *to, *weight))
                                    }),
                                    |_end_from,
                                     Tup4(start, _end, cum_weight, hopcnt),
                                     Tup3(_from, to, weight)| {
                                        Some((
                                            Tup2(*start, *to),
                                            Tup4(*start, *to, cum_weight + weight, hopcnt + 1),
                                        ))
                                    },
                                ),
                        ))
                    },
                )
                // A forest has a unique path per pair, so `distinct` would be
                // pure overhead; drop it declaratively.
                .without_distinct()
                .finish()?;

            Ok((edges_input, closure.accumulate_output()))
        })?;

    Ok(TransClosureCircuit {
        handle,
        edges_input,
        closure_output,
    })
}

/// Upper bound on nested iterations before the iterate variant gives up waiting
/// for a fixed point.
const MAX_ITERATIONS: usize = 4096;

/// Computes the transitive closure of an acyclic graph using DBSP's lower level
/// [`iterate` API](dbsp::circuit::Circuit::iterate).
///
/// It uses a hybrid termination check: Either stop once the subcircuit
/// reaches a fixed point, or after [`MAX_ITERATIONS`] steps if it never does.
fn build_iterate_variant() -> anyhow::Result<TransClosureCircuit> {
    let (handle, (edges_input, closure_output)) =
        Runtime::init_circuit(WORKERS, move |root_circuit| {
            let (edges, edges_input) = root_circuit.add_input_zset::<WeightedEdge>();

            let len_1 = edges.map_index(|Tup3(from, to, weight)| {
                (Tup2(*from, *to), Tup4(*from, *to, *weight, 1))
            });

            let closure = root_circuit.iterate(|child_circuit| {
                let edges = edges.delta0(child_circuit);
                let len_1 = len_1.delta0(child_circuit);

                let (closure_frontier, closure_frontier_feedback) = child_circuit
                    .add_feedback(Z1::new(OrdIndexedZSet::<Path, TransClosurePath>::default()));

                let new_paths = len_1.plus(
                    &closure_frontier
                        .map_index(
                            |(Tup2(_start, _end), Tup4(start, end, cum_weight, hopcnt))| {
                                (*end, Tup4(*start, *end, *cum_weight, *hopcnt))
                            },
                        )
                        .join_index(
                            &edges.map_index(|Tup3(from, to, weight)| {
                                (*from, Tup3(*from, *to, *weight))
                            }),
                            |_end_from,
                             Tup4(start, _end, cum_weight, hopcnt),
                             Tup3(_from, to, weight)| {
                                Some((
                                    Tup2(*start, *to),
                                    Tup4(*start, *to, cum_weight + weight, hopcnt + 1),
                                ))
                            },
                        ),
                );

                closure_frontier_feedback.connect(&new_paths);

                let closure = Stream::dyn_integrate_trace(
                    &new_paths.inner(),
                    &BatchReaderFactories::new::<Path, TransClosurePath, ZWeight>(),
                );

                let child_circuit = child_circuit.clone();
                let consensus = Consensus::new("iterate");
                let step = Cell::new(0usize);
                let termination_check = async move || {
                    let step_count = step.get() + 1;
                    step.set(step_count);

                    // The step bound is data-independent, hence identical on every worker;
                    // the fixed-point check is per-worker.
                    let fixedpoint = child_circuit.check_fixedpoint(0);
                    let iteration_ceiling = step_count >= MAX_ITERATIONS;
                    let done = consensus.check(fixedpoint || iteration_ceiling).await?;
                    if done {
                        // Reset the step counter for the next transaction.
                        step.set(0);
                    }

                    Ok(done)
                };

                Ok((termination_check, closure.export()))
            })?;

            let closure = Stream::dyn_consolidate(
                &closure,
                &BatchReaderFactories::new::<Path, TransClosurePath, ZWeight>(),
            )
            .typed::<OrdIndexedZSet<Path, TransClosurePath>>()
            .accumulate_output();

            Ok((edges_input, closure))
        })?;

    Ok(TransClosureCircuit {
        handle,
        edges_input,
        closure_output,
    })
}
