//! Benchmark comparing two transitive-closure computation approaches on cyclic
//! graphs similar to `examples/tutorial/tutorial11.rs`:
//!
//! - **recursive**: `Circuit::recursive` (which applies an implicit `distinct`
//!   on every nested clock tick) followed by a `Min` aggregation that both keeps
//!   the shortest path per pair and guarantees termination on cycles.
//!   See [`build_recursive_variant`].
//! - **iterate**: `Circuit::iterate` with a manual feedback loop that carries
//!   only the per-iteration frontier and relies solely on the same `Min`
//!   aggregation for termination and does not implicitly add a `distinct`.
//!   See [`build_iterate_variant`].
//!
//! On cyclic graphs the two approaches from the sister benchmark
//! `transitive_closure_acyclic` would not terminate, so both variants aggregate
//! with `Min` to collapse every `(start, end)` pair to its shortest path.
//! That aggregation makes the two variants produce identical closures
//! regardless of graph shape (the benchmark asserts this before measuring).
//! The recursive variant deduplicates twice, once via the hidden `distinct` and
//! once via `Min`, whereas the iterate variant deduplicates only via `Min`.
//! This benchmark asserts that the additional `distinct` of the recursive
//! variant is essentially a no-op because it operates on top of already
//! distinct data.
//!
//! Run with, e.g.:
//! `cargo bench --bench transitive_closure_cyclic`

use criterion::{BatchSize, BenchmarkId, Criterion, Throughput, criterion_group, criterion_main};
use dbsp::{
    Circuit, CircuitBase, Consensus, DBSPHandle, NestedCircuit, NumEntries, OrdIndexedZSet,
    OutputHandle, Runtime, Stream, ZSetHandle, ZWeight,
    mimalloc::MiMalloc,
    operator::{Min, Z1},
    trace::BatchReaderFactories,
    typed_batch::SpineSnapshot,
    utils::{Tup2, Tup3, Tup4},
};
use rand::{Rng, SeedableRng};
use rand_chacha::ChaCha8Rng;
use std::cell::Cell;

#[global_allocator]
static ALLOC: MiMalloc = MiMalloc;

type NodeId = u64;
type Weight = u64;
type CumWeight = u64;
type Hopcnt = u64;
type WeightedEdge = Tup3<NodeId, NodeId, Weight>;
type Path = Tup2<NodeId, NodeId>;
type TransClosurePath = Tup4<NodeId, NodeId, CumWeight, Hopcnt>;
type Accumulator = Stream<NestedCircuit, OrdIndexedZSet<Path, TransClosurePath>>;

struct TransClosureCircuit {
    handle: DBSPHandle,
    edges_input: ZSetHandle<WeightedEdge>,
    closure_output: OutputHandle<SpineSnapshot<OrdIndexedZSet<Path, TransClosurePath>>>,
}

/// Number of DBSP worker threads used for every circuit in this benchmark.
const WORKERS: usize = 4;

/// Deterministic seed so every run sees the same graphs.
const SEED: u64 = 0x0BADC0DE_DEADBEEF;

/// Largest edge weight generated by [`generate_cyclic_graph`].
const MAX_EDGE_WEIGHT: Weight = 10;

/// Out-edges emitted per node by [`generate_cyclic_graph`].
const OUT_DEGREE: usize = 3;

/// A single-transaction workload: all edges of one cyclic graph.
type Workload = Vec<Tup2<WeightedEdge, ZWeight>>;

/// Generates a random weighted *cyclic* graph as a single insertion batch.
///
/// Each node emits `out_degree` edges to distinct random targets drawn from the
/// whole node range (excluding itself).  Unlike the acyclic benchmark, targets
/// may point back to lower ids, so cycles form freely; with `out_degree >= 2`
/// and a few hundred nodes the graph is strongly connected with overwhelming
/// probability, yielding a near-complete transitive closure.
///
/// Both variants rely on the `Min` aggregation for termination:  Because `Min`
/// collapses every `(start, end)` pair to a single shortest path, the two
/// variants produce identical closures no matter how many distinct paths
/// connect a pair of nodes.
fn generate_cyclic_graph(nodes: NodeId, out_degree: usize) -> Workload {
    let mut rng = ChaCha8Rng::seed_from_u64(SEED);
    // At most `nodes - 1` distinct targets exist per node (self is excluded).
    let fanout = out_degree.min(nodes.saturating_sub(1) as usize);
    let mut edges = Vec::with_capacity(nodes as usize * fanout);

    for from in 0..nodes {
        let mut targets = Vec::with_capacity(fanout);
        while targets.len() < fanout {
            let to = rng.gen_range(0..nodes);
            if to != from && !targets.contains(&to) {
                targets.push(to);
            }
        }
        for to in targets {
            let weight = rng.gen_range(1..=MAX_EDGE_WEIGHT);
            edges.push(Tup2(Tup3(from, to, weight), 1));
        }
    }

    edges
}

/// Feeds a whole graph into a freshly built circuit in one transaction and
/// returns the number of paths in the resulting transitive closure.
///
/// The circuit (and its worker threads) is dropped on return, so the caller
/// must supply a fresh circuit for each measured iteration.
fn drive_once(mut circuit: TransClosureCircuit, mut workload: Workload) -> usize {
    circuit.edges_input.append(&mut workload);
    circuit
        .handle
        .transaction()
        .expect("transaction should succeed");
    circuit
        .closure_output
        .concat()
        .consolidate()
        .num_entries_shallow()
}

/// Cross-checks that both variants compute the same closure on the given graph,
/// returning the shared closure size (used both as a sanity check and to label
/// the benchmark with the output cardinality).
fn assert_variants_agree(workload: &Workload) -> usize {
    let recursive = build_recursive_variant().expect("build recursive circuit");
    let iterate = build_iterate_variant().expect("build iterate circuit");

    let mut recursive_circuit = recursive.handle;
    let mut iterate_circuit = iterate.handle;

    recursive.edges_input.append(&mut workload.clone());
    iterate.edges_input.append(&mut workload.clone());
    recursive_circuit.transaction().unwrap();
    iterate_circuit.transaction().unwrap();

    let recursive_closure = recursive.closure_output.concat().consolidate();
    let iterate_closure = iterate.closure_output.concat().consolidate();

    assert_eq!(
        recursive_closure, iterate_closure,
        "recursive and iterate variants must agree on cyclic input"
    );

    recursive_closure.num_entries_shallow()
}

/// The forest sizes (in terms of node counts) we benchmark. The transitive
/// closure of a strongly connected graph is roughly `nodes^2`,
/// so these stay modest.
const GRAPH_SIZES: &[NodeId] = &[100, 200, 400];

fn transitive_closure_benches(c: &mut Criterion) {
    let mut group = c.benchmark_group("transitive-closure-cyclic");
    // Building a circuit spins up worker threads, so keep the sample count
    // modest to bound the wall-clock time of the whole benchmark.
    group.sample_size(20);

    for &nodes in GRAPH_SIZES {
        let workload = generate_cyclic_graph(nodes, OUT_DEGREE);
        let closure_size = assert_variants_agree(&workload);
        let shape = format!("n{nodes}");
        println!(
            "graph {shape}: {} edges, closure of {closure_size} paths",
            workload.len()
        );

        // Report throughput in paths of the computed closure per second so the
        // two variants are compared on the same unit of useful work.
        group.throughput(Throughput::Elements(closure_size as u64));

        group.bench_with_input(
            BenchmarkId::new("recursive", &shape),
            &workload,
            |b, workload| {
                b.iter_batched(
                    || {
                        (
                            build_recursive_variant().expect("build recursive circuit"),
                            workload.clone(),
                        )
                    },
                    |(circuit, workload)| drive_once(circuit, workload),
                    BatchSize::PerIteration,
                );
            },
        );

        group.bench_with_input(
            BenchmarkId::new("iterate", &shape),
            &workload,
            |b, workload| {
                b.iter_batched(
                    || {
                        (
                            build_iterate_variant().expect("build iterate circuit"),
                            workload.clone(),
                        )
                    },
                    |(circuit, workload)| drive_once(circuit, workload),
                    BatchSize::PerIteration,
                );
            },
        );
    }

    group.finish();
}

criterion_group!(benches, transitive_closure_benches);
criterion_main!(benches);

/// Computes the transitive closure of a cyclic graph using DBSP's
/// [`recursive` API](dbsp::circuit::ChildCircuit::recursive) plus a `Min`
/// aggregation.
fn build_recursive_variant() -> anyhow::Result<TransClosureCircuit> {
    let (handle, (edges_input, closure_output)) =
        Runtime::init_circuit(WORKERS, move |root_circuit| {
            let (edges, edges_input) = root_circuit.add_input_zset::<WeightedEdge>();

            let len_1 = edges.map_index(|Tup3(from, to, weight)| {
                (Tup2(*from, *to), Tup4(*from, *to, *weight, 1))
            });

            let closure = root_circuit.recursive(|child_circuit, closure: Accumulator| {
                let edges = edges.delta0(child_circuit);
                let len_1 = len_1.delta0(child_circuit);

                let closure = len_1
                    .plus(
                        &closure
                            .map_index(
                                |(Tup2(_start, _end), Tup4(start, end, cum_weight, hopcnt))| {
                                    (*end, Tup4(*start, *end, *cum_weight, *hopcnt))
                                },
                            )
                            .join_index(
                                &edges.map_index(|Tup3(from, to, weight)| {
                                    (*from, Tup3(*from, *to, *weight))
                                }),
                                |_end_from,
                                 Tup4(start, _end, cum_weight, hopcnt),
                                 Tup3(_from, to, weight)| {
                                    Some((
                                        Tup2(*start, *to),
                                        Tup4(*start, *to, cum_weight + weight, hopcnt + 1),
                                    ))
                                },
                            ),
                    )
                    // The `Min` aggregation keeps the shortest path per pair and,
                    // crucially, guarantees termination on cyclic graphs.
                    .aggregate(Min)
                    // We explicitly mark the stream as distinct to avoid the
                    // implicit distinct because the aggregation step already
                    // ensures distinctness.
                    .mark_distinct();

                Ok(closure)
            })?;

            Ok((edges_input, closure.accumulate_output()))
        })?;

    Ok(TransClosureCircuit {
        handle,
        edges_input,
        closure_output,
    })
}

/// Upper bound on nested iterations before the iterate variant gives up waiting
/// for a fixed point.
const MAX_ITERATIONS: usize = 4096;

/// Computes the transitive closure of a cyclic graph using DBSP's lower level
/// [`iterate` API](dbsp::circuit::Circuit::iterate) plus a `Min` aggregation.
///
/// It uses a hybrid termination check: Either stop once the subcircuit
/// reaches a fixed point, or after [`MAX_ITERATIONS`] steps if it never does.
fn build_iterate_variant() -> anyhow::Result<TransClosureCircuit> {
    let (handle, (edges_input, closure_output)) =
        Runtime::init_circuit(WORKERS, move |root_circuit| {
            let (edges, edges_input) = root_circuit.add_input_zset::<WeightedEdge>();

            let len_1 = edges.map_index(|Tup3(from, to, weight)| {
                (Tup2(*from, *to), Tup4(*from, *to, *weight, 1))
            });

            let closure = root_circuit.iterate(|child_circuit| {
                let edges = edges.delta0(child_circuit);
                let len_1 = len_1.delta0(child_circuit);

                let (closure_frontier, closure_frontier_feedback) = child_circuit
                    .add_feedback(Z1::new(OrdIndexedZSet::<Path, TransClosurePath>::default()));

                let new_paths = len_1
                    .plus(
                        &closure_frontier
                            .map_index(
                                |(Tup2(_start, _end), Tup4(start, end, cum_weight, hopcnt))| {
                                    (*end, Tup4(*start, *end, *cum_weight, *hopcnt))
                                },
                            )
                            .join_index(
                                &edges.map_index(|Tup3(from, to, weight)| {
                                    (*from, Tup3(*from, *to, *weight))
                                }),
                                |_end_from,
                                 Tup4(start, _end, cum_weight, hopcnt),
                                 Tup3(_from, to, weight)| {
                                    Some((
                                        Tup2(*start, *to),
                                        Tup4(*start, *to, cum_weight + weight, hopcnt + 1),
                                    ))
                                },
                            ),
                    )
                    // No `distinct` here (not even behind the scenes); the `Min`
                    // aggregation alone deduplicates and stops the iteration.
                    .aggregate(Min);

                closure_frontier_feedback.connect(&new_paths);

                let closure = Stream::dyn_integrate_trace(
                    &new_paths.inner(),
                    &BatchReaderFactories::new::<Path, TransClosurePath, ZWeight>(),
                );

                let child_circuit = child_circuit.clone();
                let consensus = Consensus::new("iterate");
                let step = Cell::new(0usize);
                let termination_check = async move || {
                    let step_count = step.get() + 1;
                    step.set(step_count);

                    // The step bound is data-independent, hence identical on every worker;
                    // the fixed-point check is per-worker.
                    let fixedpoint = child_circuit.check_fixedpoint(0);
                    let iteration_ceiling = step_count >= MAX_ITERATIONS;
                    let done = consensus.check(fixedpoint || iteration_ceiling).await?;
                    if done {
                        // Reset the step counter for the next transaction.
                        step.set(0);
                    }

                    Ok(done)
                };

                Ok((termination_check, closure.export()))
            })?;

            let closure = Stream::dyn_consolidate(
                &closure,
                &BatchReaderFactories::new::<Path, TransClosurePath, ZWeight>(),
            )
            .typed::<OrdIndexedZSet<Path, TransClosurePath>>()
            .accumulate_output();

            Ok((edges_input, closure))
        })?;

    Ok(TransClosureCircuit {
        handle,
        edges_input,
        closure_output,
    })
}
