# Build the pipeline-manager image from local source instead of using the latest release.
services:
  pipeline-manager:
    image: ghcr.io/feldera/pipeline-manager
    build:
      context: ../
      dockerfile: deploy/Dockerfile
