# For developers to build the two required
# DBSP containers from local sources
services:
  db:
    ports:
      - 6666:5432 # Used for pipeline manager integration tests

  pipeline-manager:
   build:
     context: ../
     dockerfile: deploy/Dockerfile
   image: ghcr.io/feldera/pipeline-manager

  demo:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      target: client
    image: ghcr.io/feldera/demo-container
