# For developers to build the two required
# DBSP containers from local sources
services:
  pipeline-manager:
   build:
     context: ../
     dockerfile: deploy/Dockerfile
   image: ghcr.io/feldera/pipeline-manager

  demo:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
      target: client
    image: ghcr.io/feldera/demo-container
