package org.dbsp.sqlCompiler.compiler.visitors.outer;

import org.dbsp.sqlCompiler.circuit.annotation.JoinStrategy;
import org.dbsp.sqlCompiler.circuit.annotation.OperatorHash;
import org.dbsp.sqlCompiler.circuit.annotation.RegionAnnotation;
import org.dbsp.sqlCompiler.circuit.operator.DBSPBinaryOperator;
import org.dbsp.sqlCompiler.circuit.operator.DBSPControlledKeyFilterOperator;
import org.dbsp.sqlCompiler.circuit.operator.DBSPOperator;
import org.dbsp.sqlCompiler.circuit.operator.DBSPSourceMultisetOperator;
import org.dbsp.sqlCompiler.compiler.DBSPCompiler;
import org.dbsp.util.Bijection;
import org.dbsp.util.IIndentStream;
import org.dbsp.util.Utilities;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

/**
 * Data structure holding per-circuit information which is generated after all nodes have been processed.
 */
public class CircuitPostfix extends CircuitVisitor {
    // Keeps track of tables that have to be materialized at a different point in the circuit.
    // Discover input nodes that immediately feed the left input of a controlled_key_filter operator.
    // This pattern is generated by inputs with LATENESS annotations.
    // If the input table is materialized, the materialized stream has
    // to be the output of the controlled_key_filter operator. */
    final Bijection<DBSPSourceMultisetOperator, DBSPControlledKeyFilterOperator> materialization = new Bijection<>();
    public final List<BalancerHint> balancerHints = new ArrayList<>();
    final Set<String> regionsCreated = new HashSet<>();

    public record BalancerHint(DBSPBinaryOperator operator, JoinStrategy strategy) {
        public void emit(IIndentStream builder) {
            builder.append("circuit.set_balancer_hint(").increase();
            var input = this.strategy.input == 0 ? this.operator.left() : operator.right();
            var inputHash = OperatorHash.getHash(input.node(), true);
            builder.append(Utilities.doubleQuote(Objects.requireNonNull(inputHash).toString(), true))
                    .append(",").newline();
            builder.append(this.strategy.toRust()).newline();
            builder.decrease().append(")?;").newline();
        }
    }

    public CircuitPostfix(DBSPCompiler compiler) {
        super(compiler);
    }

    @Override
    public void postorder(DBSPControlledKeyFilterOperator operator) {
        DBSPOperator left = operator.left().operator;
        if (!left.is(DBSPSourceMultisetOperator.class)) return;
        DBSPSourceMultisetOperator source = left.to(DBSPSourceMultisetOperator.class);
        if (source.metadata.materialized)
            this.materialization.map(source, operator);
    }

    public boolean has(DBSPSourceMultisetOperator source) {
        return this.materialization.has(source);
    }

    public boolean hasRight(DBSPControlledKeyFilterOperator dest) {
        return this.materialization.hasRight(dest);
    }

    public DBSPSourceMultisetOperator getLeft(DBSPControlledKeyFilterOperator dest) {
        return this.materialization.getLeft(dest);
    }

    /** Record a region; return 'true' if the region already existed */
    public boolean recordRegion(RegionAnnotation annotation) {
        if (this.regionsCreated.contains(annotation.asVarName()))
            return true;
        this.regionsCreated.add(annotation.asVarName());
        return false;
    }

    public void recordHint(DBSPBinaryOperator operator, JoinStrategy strategy) {
        BalancerHint hint = new BalancerHint(operator, strategy);
        this.balancerHints.add(hint);
    }

    public void clearRegions() {
        this.regionsCreated.clear();
    }
}
