// Parse and represent the JSON encoding of the profile information generated by Feldera.

import { fail, enforceNumber, Option, OMap, type Comparable, assert, NumericRange, tuple } from "./util.js";
import { type MirNode, SourcePositionRanges, SourcePositionRange, Sources, type Dataflow } from "./dataflow.js";

type JsonMeasurement = Array<any>;
export type NodeId = string;

export type CircuitMetricCategory = string;

export interface ProfileMetricDescription {
    readonly name: string;
    readonly category: CircuitMetricCategory;
    readonly advanced: boolean;
    readonly description: string;
}

// Base class for all metric representations in the new profile representation
interface JsonMetricBase {
    metric_id: string;
    labels?: Array<[string, string]>;
    value: JsonMetricValue;
}

// A metric value as it appears in the profile, serialized from Rust as JSON
interface MetricValue { };

// Base types
interface StringMetricValue extends MetricValue {
    type: "string";
    value: string;
}

interface IntMetricValue extends MetricValue {
    type: "int";
    value: number;
}

interface CountMetricValue extends MetricValue {
    type: "count";
    value: number;
}

interface DurationMetricValue {
    type: "duration";
    value: {
        secs: number;
        nanos: number;
    }
}

interface BytesMetricValue {
    type: "bytes";
    value: number;
}

interface BoolMetricValue {
    type: "bool";
    value: boolean;
}

interface PercentMetricValue {
    type: "percent";
    value: {
        numerator: number;
        denominator: number;
    }
}

// Composite types
interface StatsMetricValue extends MetricValue {
    avg_records_count: CountMetricValue;
    batches_count: CountMetricValue;
    max_records_count: CountMetricValue;
    min_records_count: CountMetricValue;
    total_records_count: CountMetricValue;
}

interface MergesMetricValue extends MetricValue {
    avg_step_seconds: DurationMetricValue;
    avg_step_cpu_seconds: DurationMetricValue;
    batches: CountMetricValue;
    merges: CountMetricValue;
    steps: CountMetricValue;
}

interface SerializedStringValue {
    type: "string";
    value: string;
}

interface RetainmentValue extends MetricValue {
    key: SerializedStringValue | Array<SerializedStringValue>;
    value: SerializedStringValue | Array<SerializedStringValue>;
}

interface DistributionValue {
    values: Array<number>;
}

interface OccupancyValue extends MetricValue {
    max: BytesMetricValue;
    used: BytesMetricValue;
}

interface CacheStatsValue extends MetricValue {
    type: "cachecounts";
    value: {
        count: number;
        bytes: number;
        elapsed: {
            secs: number;
            nanos: number;
        };
    }
}

type JsonMetricValue =
    BoolMetricValue |
    CountMetricValue |
    BytesMetricValue |
    PercentMetricValue |
    DurationMetricValue |
    StatsMetricValue |
    StringMetricValue |
    DistributionValue |
    RetainmentValue |
    IntMetricValue |
    MergesMetricValue |
    OccupancyValue |
    CacheStatsValue;

// Serialized representation of the measurements for a node.
type JsonProfileEntries = Array<JsonMetricBase>

interface LegacyJsonProfileEntries {
    entries: Array<JsonMeasurement>;
}

// Serialized representation of a single profile.
interface JsonWorkerProfile {
    // Map node name to measurements.
    readonly metadata: Record<NodeId, JsonProfileEntries>;
}

interface LegacyJsonWorkerProfile {
    // Map node name to measurements.
    readonly metadata: Record<NodeId, LegacyJsonProfileEntries>;
}

// Serialized representation of a simple circuit node.
interface JsonSimpleCircuitNode {
    id: NodeId;
    label: string;
}

interface JsonSimpleNodeWrapper {
    Simple: JsonSimpleCircuitNode;
}

interface JsonClusterWrapper {
    Cluster: JsonCircuitCluster;
}

// Serialized representation of a cluster of nodes.
interface JsonCircuitCluster {
    id: NodeId;
    label: string;
    nodes: Array<JsonSimpleNodeWrapper | JsonClusterWrapper>;
}

// Serialized representation of an edge.
interface JsonCircuitEdge {
    from_node: NodeId;
    to_node: NodeId;
    from_cluster: boolean;
    to_cluster: boolean;
}

// Serialized representation of a circuit graph.
interface JsonGraph {
    readonly nodes: JsonCircuitCluster;
    readonly edges: Array<JsonCircuitEdge>;
}

// Serialized JSON representation for the
// profiles received from the Feldera pipeline manager.
export type JsonProfiles = {
    // The "metrics" property only exists in new profiles
    readonly metrics: Array<ProfileMetricDescription>;
    readonly worker_profiles: Array<JsonWorkerProfile>;
    readonly graph: JsonGraph;
} | {
    readonly worker_profiles: Array<LegacyJsonWorkerProfile>;
    readonly graph: JsonGraph;
}

///////////////// Parsing code to decode measurements

function formatValue(val: number, base: number, prefixes: Array<string>): string {
    let index = 0;
    while ((Math.abs(val) >= base) && (index < (prefixes.length - 1))) {
        val = val / base;
        index++;
    }
    // For sub-unit values, `maximumFractionDigits: 2` rounds non-zero numbers down to "0".
    // Switch to `maximumSignificantDigits: 2` in that range so e.g. 0.004 -> "0.004" instead of "0".
    const opts: Intl.NumberFormatOptions = (val !== 0 && Math.abs(val) < 1)
        ? { maximumSignificantDigits: 2 }
        : { minimumFractionDigits: 0, maximumFractionDigits: 2 };
    return val.toLocaleString('en-US', opts) + prefixes[index];
}

/** How multiple metric measurements are combined for a node from the children measurements. */
export enum AggregationMode {
    /** Magnitudes add: counts, bytes, durations. */
    Sum,
    /** sum(numerator) / sum(denominator). */
    WeightedRatio,
    /** sum(numerator)/ denominator */
    CommonDenominator,
    /** Minimum value */
    Min,
    /** Maximum value */
    Max,
    /** Boolean OR */
    Or,
    /** Common value or "<multiple values>". */
    CommonValue,
}

/** Base class for (numeric) property values; representation which abstracts away from the
 * JSON Serialization. */
export abstract class PropertyValue implements Comparable<PropertyValue> {
    abstract getNumericValue(): Option<number>;

    getStringValue(): string {
        return this.toString();
    }

    compareTo(other: PropertyValue): number {
        let v1 = this.getNumericValue();
        let v2 = other.getNumericValue();
        if (v1.isSome() && v2.isSome()) {
            return v1.unwrap() - v2.unwrap();
        } else if (v1.isSome()) {
            return 1;
        } else if (v2.isSome()) {
            return -1;
        } else {
            return 0;
        }
    }

    // A missing value compares below any reading, so it never wins.
    max(other: PropertyValue): PropertyValue {
        if (this.compareTo(other) >= 0) {
            return this;
        } else {
            return other;
        }
    }

    min(other: PropertyValue): PropertyValue {
        if (other instanceof MissingValue) {
            return this;
        }
        if (this instanceof MissingValue) {
            return other;
        }
        return this.compareTo(other) <= 0 ? this : other;
    }

    /** Fold this value with the same metric's value from another node, as specified by `mode`. */
    aggregate(other: PropertyValue, mode: AggregationMode): PropertyValue {
        // One metric holds one kind, so folding two kinds is a mistake whichever mode is asked
        // for.  Each kind checks this for the modes it implements; Min and Max are implemented
        // here for every kind, and so is their check.
        const sameKind = other instanceof MissingValue
            || other.constructor === this.constructor;
        if (sameKind && this.isComparable()) {
            if (mode === AggregationMode.Min) {
                return this.min(other);
            }
            if (mode === AggregationMode.Max) {
                return this.max(other);
            }
        }
        fail("Cannot fold " + this.constructor.name + " with " + other.constructor.name +
            " using " + AggregationMode[mode]);
    }

    toString(): string {
        let v = this.getNumericValue();
        if (v.isSome()) {
            let value = v.unwrap();
            let prefixes = ["", "K", "M", "B"];
            return formatValue(value, 1000, prefixes);
        } else {
            return "N/A";
        }
    }

    /** True iff `compareTo` carries magnitude information for this kind, i.e. ordering pairs is
     * meaningful beyond mere distinction. Numeric kinds (count/bytes/time/percent) are
     * comparable; nominal kinds (booleans, enum strings) are not, so callers should suppress the
     * Min/Max columns for them. The `Avg` column still makes sense — it reports the mode. */
    isComparable(): boolean {
        return true;
    }

    /** This value multiplied by `factor`.  Used to render a ratio,
     * e.g. 2000 records over 101 batches as a count of 19.8. */
    abstract scale(factor: number): PropertyValue;

    /** Average this value and `others` across workers.  Distinct from folding across nodes
     * (`aggregate`) because the per-kind semantics differ:
     *   - counts/bytes/seconds: arithmetic mean of the underlying numbers.
     *   - percents: arithmetic mean of per-worker percents (not weighted — see PercentValue).
     *   - booleans / enum strings: the most common value across workers (the mode), so the
     *     "Avg" column shows the prevailing reading instead of N/A.
     *   - missing: delegate to the first non-missing neighbour so the result inherits the
     *     right kind. */
    abstract average(others: PropertyValue[]): PropertyValue;
}

/** A property value represented as a numerator and denominator, which are supposed to represent a percentage. */
export class PercentValue extends PropertyValue {
    readonly numerator: number;
    readonly denominator: number;

    constructor(numerator: any, denominator: any) {
        super();
        this.numerator = enforceNumber(numerator);
        this.denominator = enforceNumber(denominator);
    }

    static fromNumbers(numerator: number, denominator: number): PercentValue {
        return new PercentValue(numerator, denominator);
    }

    static fromPercentMetric(s: PercentMetricValue) {
        return new PercentValue(s.value.numerator, s.value.denominator);
    }

    getNumericValue(): Option<number> {
        if (this.denominator === 0) {
            return Option.some(0);
        }
        return Option.some(100 * this.numerator / this.denominator);
    }

    override toString(): string {
        let v = this.getNumericValue();
        if (v.isNone()) {
            return "N/A";
        }
        const value = v.unwrap();
        // Below 0.1% the 1-decimal form rounds to "0.0%"; fall back to 2 significant figures
        // there so e.g. 0.034 -> "0.034%" instead of "0.0%".
        if (value !== 0 && Math.abs(value) < 0.1) {
            return value.toLocaleString('en-US', { maximumSignificantDigits: 2 }) + "%";
        }
        return value.toFixed(1) + "%";
    }

    override aggregate(other: PropertyValue, mode: AggregationMode): PropertyValue {
        if (other instanceof MissingValue) {
            return this;
        }
        if (other instanceof PercentValue) {
            switch (mode) {
                case AggregationMode.WeightedRatio:
                    return PercentValue.pool(this, other);
                case AggregationMode.CommonDenominator:
                    if (this.denominator === other.denominator) {
                        return new PercentValue(this.numerator + other.numerator, this.denominator);
                    }
                    // Nodes that disagree about the total do not divide by a common denominator
                    // after all; pooling the terms is the reading that stays interpretable.
                    return this.aggregate(other, AggregationMode.WeightedRatio);
            }
        }
        return super.aggregate(other, mode);
    }

    /** Pool two ratios: pool(a/b, c/d) = (a+c) / (b+d) */
    private static pool(a: PercentValue, b: PercentValue): PercentValue {
        return new PercentValue(a.numerator + b.numerator, a.denominator + b.denominator);
    }

    override scale(factor: number): PropertyValue {
        return new PercentValue(this.numerator * factor, this.denominator);
    }

    // Weighted mean across workers: sum(numerator) / sum(denominator). A worker that observed
    // 5 of 10 events contributes 5 hits and 10 trials to the pooled ratio, so workers with more
    // observations move the average more — the right semantics for population-level percents
    // like hit rates or utilization.
    override average(others: PropertyValue[]): PropertyValue {
        let numSum = 0;
        let denSum = 0;
        let any = false;
        for (const v of [this, ...others]) {
            if (v instanceof PercentValue) {
                numSum += v.numerator;
                denSum += v.denominator;
                any = true;
            }
        }
        if (!any) {
            return MissingValue.INSTANCE;
        }
        return new PercentValue(numSum, denSum);
    }
}

/** A property value that is a simple count. */
export class CountValue extends PropertyValue {
    readonly value: number;

    constructor(value: any) {
        super();
        this.value = enforceNumber(value);
    }

    static fromNumber(value: number): CountValue {
        return new CountValue(value);
    }

    static fromCountMetric(value: CountMetricValue): CountValue {
        return new CountValue(value.value);
    }

    getNumericValue(): Option<number> {
        return Option.some(this.value);
    }

    override aggregate(other: PropertyValue, mode: AggregationMode): PropertyValue {
        if (other instanceof MissingValue) {
            return this;
        }
        if (other instanceof CountValue && mode === AggregationMode.Sum) {
            return new CountValue(this.value + other.value);
        }
        return super.aggregate(other, mode);
    }

    override scale(factor: number): PropertyValue {
        return new CountValue(this.value * factor);
    }

    override average(others: PropertyValue[]): PropertyValue {
        const values: number[] = [];
        for (const v of [this, ...others]) {
            if (v instanceof CountValue) {
                values.push(v.value);
            }
        }
        if (values.length === 0) {
            return MissingValue.INSTANCE;
        }
        return new CountValue(values.reduce((a, b) => a + b, 0) / values.length);
    }
}

export class BytesValue extends PropertyValue {
    readonly value: number;

    constructor(value: any) {
        super();
        this.value = enforceNumber(value);
    }

    static fromNumber(value: number): BytesValue {
        return new BytesValue(value);
    }

    static fromBytesMetric(value: BytesMetricValue): BytesValue {
        return new BytesValue(value.value);
    }

    getNumericValue(): Option<number> {
        return Option.some(this.value);
    }

    override aggregate(other: PropertyValue, mode: AggregationMode): PropertyValue {
        if (other instanceof MissingValue) {
            return this;
        }
        if (other instanceof BytesValue && mode === AggregationMode.Sum) {
            return new BytesValue(this.value + other.value);
        }
        return super.aggregate(other, mode);
    }

    override scale(factor: number): PropertyValue {
        return new BytesValue(this.value * factor);
    }

    override average(others: PropertyValue[]): PropertyValue {
        const values: number[] = [];
        for (const v of [this, ...others]) {
            if (v instanceof BytesValue) {
                values.push(v.value);
            }
        }
        if (values.length === 0) {
            return MissingValue.INSTANCE;
        }
        return new BytesValue(values.reduce((a, b) => a + b, 0) / values.length);
    }

    override toString(): string {
        let prefixes = ["B", "KiB", "MiB", "GiB", "TiB"];
        return formatValue(this.value, 1024, prefixes);
    }
}

/** A property value that is a Boolean. */
export class BooleanValue extends PropertyValue {
    readonly value: boolean;

    constructor(id: any) {
        super();
        if (typeof id !== "boolean") {
            throw new TypeError(`Expected a valid boolean, got, ${id}`);
        }
        this.value = id;
    }

    static fromBoolMetric(value: BoolMetricValue): BooleanValue {
        return new BooleanValue(value.value);
    }

    override isComparable(): boolean {
        return false;
    }

    // `true` maps to the high end of the bar-chart range and `false` to the low end, so a worker
    // reporting `true` shows the tallest bar.
    getNumericValue(): Option<number> {
        return this.value ? Option.some(1) : Option.some(0);
    }

    override aggregate(other: PropertyValue, mode: AggregationMode): PropertyValue {
        if (other instanceof MissingValue) {
            return this;
        }
        if (other instanceof BooleanValue && mode === AggregationMode.Or) {
            return new BooleanValue(this.value || other.value);
        }
        return super.aggregate(other, mode);
    }

    // A flag has no magnitude to scale.
    override scale(_factor: number): PropertyValue {
        return this;
    }

    // The "average" of a set of booleans is the most common value (the mode), so the Avg
    // column shows the prevailing reading across workers instead of N/A. On a tie we keep the
    // first reading, which is deterministic from the caller's perspective.
    override average(others: PropertyValue[]): PropertyValue {
        let trueCount = 0;
        let falseCount = 0;
        let first: BooleanValue | undefined;
        for (const v of [this, ...others]) {
            if (v instanceof BooleanValue) {
                if (!first) {
                    first = v;
                }
                v.value ? trueCount++ : falseCount++;
            }
        }
        if (!first) {
            return MissingValue.INSTANCE;
        }
        if (trueCount === falseCount) {
            return first;
        }
        return new BooleanValue(trueCount > falseCount);
    }

    override getStringValue(): string {
        return this.value.toString();
    }

    override toString(): string {
        return this.value.toString();
    }
}

/** A property value that is a string, with no numeric value. */
export class StringValue extends PropertyValue {
    readonly value: string;

    constructor(id: any) {
        super();
        if (typeof id !== "string") {
            throw new TypeError(`Expected a valid string, got, ${id}`);
        }
        this.value = id;
    }

    static fromString(value: string): StringValue {
        return new StringValue(value);
    }

    override isComparable(): boolean {
        return false;
    }

    getNumericValue(): Option<number> {
        return Option.none();
    }

    override aggregate(other: PropertyValue, mode: AggregationMode): PropertyValue {
        if (other instanceof MissingValue) {
            return this;
        }
        if (other instanceof StringValue && mode === AggregationMode.CommonValue) {
            if (this.value === other.value) {
                return this;
            }
            return new StringValue("<multiple values>");
        }
        return super.aggregate(other, mode);
    }

    // A string has no magnitude to scale.
    override scale(_factor: number): PropertyValue {
        return this;
    }

    // The "average" of a set of enum-like strings is the most common value (the mode), so the
    // Avg column shows the prevailing reading across workers instead of N/A. First-seen wins
    // on ties.
    override average(others: PropertyValue[]): PropertyValue {
        const counts = new Map<string, number>();
        let firstByValue: Map<string, StringValue> | undefined;
        let firstOverall: StringValue | undefined;
        for (const v of [this, ...others]) {
            if (v instanceof StringValue) {
                if (!firstOverall) {
                    firstOverall = v;
                    firstByValue = new Map();
                }
                if (!firstByValue!.has(v.value)) {
                    firstByValue!.set(v.value, v);
                }
                counts.set(v.value, (counts.get(v.value) ?? 0) + 1);
            }
        }
        if (!firstOverall) {
            return MissingValue.INSTANCE;
        }
        let best = firstOverall;
        let bestCount = counts.get(firstOverall.value)!;
        for (const [value, count] of counts) {
            if (count > bestCount) {
                best = firstByValue!.get(value)!;
                bestCount = count;
            }
        }
        return best;
    }

    override getStringValue(): string {
        return this.value;
    }

    override toString(): string {
        return this.value;
    }
}

/** No value has been provided for a property. */
export class MissingValue extends PropertyValue {
    public static readonly INSTANCE: MissingValue = new MissingValue();

    constructor() {
        super();
    }

    override getNumericValue(): Option<number> {
        return Option.none();
    }

    // A node that reported nothing contributes nothing, whatever the metric folds like.
    override aggregate(other: PropertyValue, _mode: AggregationMode): PropertyValue {
        return other;
    }

    // Nothing to scale; the result is still missing.
    override scale(_factor: number): PropertyValue {
        return this;
    }

    // If any neighbour is non-missing, delegate to it so the result inherits the right kind;
    // otherwise the whole collection is missing.
    override average(others: PropertyValue[]): PropertyValue {
        for (let i = 0; i < others.length; i++) {
            const o = others[i]!;
            if (!(o instanceof MissingValue)) {
                const rest = others.slice(0, i).concat(others.slice(i + 1));
                return o.average(rest);
            }
        }
        return MissingValue.INSTANCE;
    }
}

/** A property value that represents a time with seconds and nanoseconds. */
export class TimeValue extends PropertyValue {
    constructor(readonly seconds: number) {
        super();
    }

    static fromSecondsNanos(secs: any, nanos: any) {
        return new TimeValue(enforceNumber(secs) + enforceNumber(nanos) / 1_000_000_000);
    }

    static fromDurationMetric(s: DurationMetricValue): TimeValue {
        return this.fromSecondsNanos(s.value.secs, s.value.nanos);
    }

    getNumericValue(): Option<number> {
        return Option.some(this.seconds);
    }

    override aggregate(other: PropertyValue, mode: AggregationMode): PropertyValue {
        if (other instanceof MissingValue) {
            return this;
        }
        if (other instanceof TimeValue && mode === AggregationMode.Sum) {
            return new TimeValue(this.seconds + other.seconds);
        }
        return super.aggregate(other, mode);
    }

    override scale(factor: number): PropertyValue {
        return new TimeValue(this.seconds * factor);
    }

    override average(others: PropertyValue[]): PropertyValue {
        const values: number[] = [];
        for (const v of [this, ...others]) {
            if (v instanceof TimeValue) {
                values.push(v.seconds);
            }
        }
        if (values.length === 0) {
            return MissingValue.INSTANCE;
        }
        return new TimeValue(values.reduce((a, b) => a + b, 0) / values.length);
    }

    override toString(): string {
        let v = this.getNumericValue();
        if (v.isNone()) {
            return "N/A";
        }
        let value = v.unwrap();
        if (value === 0) {
            return "0s";
        }
        if (value < 0.001) {
            // Use significant digits below 1us so e.g. 4ns -> "0.004us" instead of "0us".
            const us = value * 1_000_000;
            const opts: Intl.NumberFormatOptions = Math.abs(us) < 1
                ? { maximumSignificantDigits: 2 }
                : { maximumFractionDigits: 2 };
            return us.toLocaleString('en-US', opts) + "us";
        }
        if (value < 1) {
            return (value * 1000).toLocaleString('en-US', { maximumFractionDigits: 2 }) + "ms";
        }
        if (value >= 3600) {
            // Hours-or-longer: render as [Nday[s] ]HH:MM:SS, discarding the sub-second part.
            const seconds = Math.floor(value);
            const days = Math.floor(seconds / 86400);
            const inDay = seconds - days * 86400;
            const hours = Math.floor(inDay / 3600);
            const minutes = Math.floor((inDay % 3600) / 60);
            const secs = inDay % 60;
            const dayPart = days > 0 ? days + (days === 1 ? "day " : "days ") : "";
            return dayPart +
                String(hours).padStart(2, "0") + ":" +
                String(minutes).padStart(2, "0") + ":" +
                String(secs).padStart(2, "0");
        }
        return value.toLocaleString('en-US', { maximumFractionDigits: 2 }) + "s";
    }
}

/** An average kept as the two terms it was computed from. */
export class RatioValue extends PropertyValue {
    readonly numerator: PropertyValue;
    readonly denominator: number;

    constructor(numerator: PropertyValue, denominator: any) {
        super();
        this.numerator = numerator;
        this.denominator = enforceNumber(denominator);
    }

    /** The quotient, as a value of the numerator's kind, so that a ratio of durations reads as a
     * duration and a ratio of counts as a count. */
    private quotient(): PropertyValue {
        // Nothing was observed: read as zero.
        if (this.denominator === 0) {
            return this.numerator.scale(0);
        }
        return this.numerator.scale(1 / this.denominator);
    }

    getNumericValue(): Option<number> {
        return this.quotient().getNumericValue();
    }

    override toString(): string {
        return this.quotient().toString();
    }

    override aggregate(other: PropertyValue, mode: AggregationMode): PropertyValue {
        if (other instanceof MissingValue) {
            return this;
        }
        if (other instanceof RatioValue && mode === AggregationMode.WeightedRatio) {
            return RatioValue.pool(this, other);
        }
        return super.aggregate(other, mode);
    }

    /** Pool two ratios pool(a/b, c/d) = (a+c)/(b+d). */
    private static pool(a: RatioValue, b: RatioValue): RatioValue {
        return new RatioValue(
            a.numerator.aggregate(b.numerator, AggregationMode.Sum),
            a.denominator + b.denominator);
    }

    // Weighted mean
    override average(others: PropertyValue[]): PropertyValue {
        // `this` is a ratio, so there is always something to average.
        let numerator: PropertyValue = MissingValue.INSTANCE;
        let denominator = 0;
        for (const v of [this, ...others]) {
            if (v instanceof RatioValue) {
                numerator = numerator.aggregate(v.numerator, AggregationMode.Sum);
                denominator += v.denominator;
            }
        }
        return new RatioValue(numerator, denominator);
    }

    override scale(factor: number): PropertyValue {
        return new RatioValue(this.numerator.scale(factor), this.denominator);
    }
}

// This function should be deleted, it is here only to temporarily
// support visualizing profiles generated by old versions of the runtime.
function legacyMeasurementCategory(prop: string): string {
    const map: Map<string, Array<string>> = new Map();
    map.set("CPU", [
        "time%",
        "invocations",
        "steps",
        "wait_time",
        "exchange_wait_time",
        "merge backpressure wait",
        "time",
        "total_idle_time",
        "runtime_elapsed",
        "total_runtime",
        "total rebalancing time",
        "in-progress rebalancing time",
        "integral records to repartition",
        "accumulator records to repartition",
        "local shard size",
        "rebalancings"]);
    map.set("storage", [
        "merge reduction",
        "output redundancy",
        "merging batches",
        "merging size",
        "input batches/batches",
        "input batches/min size",
        "input batches/max size",
        "input batches/avg size",
        "input batches/total records",
        "output batches/batches",
        "output batches/min size",
        "output batches/max size",
        "output batches/avg size",
        "output batches/total records",
        "slot 0 loose",
        "slot 1 loose",
        "slot 2 loose",
        "slot 3 loose",
        "slot 4 loose",
        "slot 0 completed",
        "slot 1 completed",
        "slot 2 completed",
        "slot 3 completed",
        "slot 4 completed",
        "slot 0 merging",
        "slot 1 merging",
        "slot 2 merging",
        "slot 3 merging",
        "slot 4 merging",
        "storage size",
        "batch sizes",
        "bounds",
        "Bloom filter size",
        "Bloom filter bits/key",
        "Bloom filter hits",
        "Bloom filter misses",
        "Bloom filter hit rate"]);
    map.set("cache", [
        "background cache hit",
        "foreground cache hit",
        "background cache miss",
        "foreground cache miss",
        "foreground cache occupancy",
        "background cache occupancy"]);
    map.set("memory", [
        "left inputs",
        "right inputs",
        "computed outputs",
        "inputs",
        "total size",
        "allocated bytes",
        "used bytes",
        "shared bytes",
        "batches",
        "allocations"]);
    for (const [k, v] of map) {
        for (const value of v) {
            if (prop.startsWith(value)) {
                return k;
            }
        }
    }
    return "";
}

export class MetricDescriptions {
    private static KEY_ORDER: Map<string, number> = new Map();
    private static METRIC_DESCRIPTIONS: Map<string, ProfileMetricDescription> = new Map();

    static known(): boolean {
        return MetricDescriptions.METRIC_DESCRIPTIONS.size > 0;
    }

    /** Get the ordinal number of the metric in the metadata array (coming from the profile,
     * where it comes from the metadata.rs file).  Note that the metric string here
     * can be a composite name, e.g., output_batches_stats.record_count; only the part
     * before the dot is the actual metric name. */
    static getMetricIndex(metric: string): number {
        let dot = metric.indexOf(".");
        if (dot >= 0)
            metric = metric.substring(0, dot);
        let result = MetricDescriptions.KEY_ORDER.get(metric);
        if (result !== undefined)
            return result;
        return MetricDescriptions.KEY_ORDER.size;
    }

    static setMetricDescriptions(descriptions: Array<ProfileMetricDescription>) {
        let index = 0;
        for (const pmd of descriptions) {
            MetricDescriptions.KEY_ORDER.set(pmd.name, index);
            MetricDescriptions.METRIC_DESCRIPTIONS.set(pmd.name, pmd);
            index++;
        }
    }

    static getMetricInfo(metric: string): ProfileMetricDescription | undefined {
        return MetricDescriptions.METRIC_DESCRIPTIONS.get(metric);
    }

    static getMetricDescription(metric: string): string | undefined {
        return MetricDescriptions.getMetricInfo(metric)?.description;
    }
}

function stripSuffix(prop: string): string {
    let dot = prop.indexOf(".");
    if (dot >= 0) {
        // Dot is used when appending measurements for a metric with multiple values
        prop = prop.substring(0, dot);
    }
    return prop;
}

/** Which category does a measurement belong to? */
export function measurementCategory(prop: string): string {
    let info = MetricDescriptions.getMetricInfo(stripSuffix(prop));
    if (info !== undefined) {
        return info.category;
    }

    // If we couldn't find the description, treat as if in an old-style profile
    return legacyMeasurementCategory(prop);
}

/** Return a description of the measurement and a boolean indicating whether the measurements is "advanced" */
export function measurementDescription(prop: string): { description: string, advanced: boolean } {
    let info = MetricDescriptions.getMetricInfo(stripSuffix(prop));
    if (info !== undefined) {
        return { description: info.description, advanced: info.advanced };
    }

    return { description: "", advanced: false };
}

/** A parsed legacy value together with the way its metric folds over a region.
 * TODO: remove together with the rest of the legacy parsing path. */
interface LegacyReading {
    readonly value: PropertyValue;
    readonly aggregation: AggregationMode;
}

// Decoded measurement value.
export class Measurement {
    /** Metric holding a node's part of the circuit's runtime: the profile divides every node's
     * runtime by the same circuit-wide total.  Named "time%" in legacy profiles. */
    public static readonly RUNTIME_PERCENT = "runtime_percent";

    /** Metric holding the circuit's elapsed wall-clock time, which the profile reports again
     * for every node and every worker.  Named "runtime_elapsed" in legacy profiles. */
    public static readonly RUNTIME_ELAPSED = "circuit_runtime_elapsed_seconds";

    constructor(
        readonly property: string,
        readonly value: Option<PropertyValue>,
        /** How the metric folds over the nodes of a region.  Stated where the measurement is
         * parsed, since that is where the meaning of the metric is known. */
        readonly aggregation: AggregationMode) { };

    public static fromJson(prefix: string, json: JsonMeasurement): Measurement {
        let name = prefix + (json[0] as string);
        const reading = Measurement.parseLegacyPropertyValue(name, json.slice(1));
        return new Measurement(
            name,
            reading.map(r => r.value),
            // A value that did not parse is dropped, so its mode is never used.
            reading.map(r => r.aggregation).unwrapOr(AggregationMode.Sum)
        );
    }

    private static tagged(value: PropertyValue, aggregation: AggregationMode):
        Option<LegacyReading> {
        return Option.some({ value, aggregation });
    }

    toString(): string {
        return this.property + ", " + this.value.toString();
    }

    static parseValues(metric: JsonMetricBase): Array<Measurement> {
        let metric_id = metric.metric_id;
        let kind = metric_id.split("_").pop(); // count, bytes, etc
        if (metric.labels) {
            let labels = metric.labels.map(e => e.join(":")).join(".");
            if (metric.labels.length !== 0) {
                metric_id = metric_id + "." + labels;
            }
        }
        switch (kind) {
            case "bool": {
                let m = metric.value as BoolMetricValue;
                let value = BooleanValue.fromBoolMetric(m);
                return [new Measurement(metric_id, Option.some(value), AggregationMode.Or)];
            }
            case "bytes": {
                let m = metric.value as BytesMetricValue;
                let bytes = BytesValue.fromBytesMetric(m);
                return [new Measurement(metric_id, Option.some(bytes), AggregationMode.Sum)];
            }
            case "count": {
                let m = metric.value as CountMetricValue;
                let count = CountValue.fromCountMetric(m);
                return [new Measurement(metric_id, Option.some(count), AggregationMode.Sum)];
            }
            case "hits":
            case "misses": {
                let s = metric.value as CacheStatsValue;
                let count = new CountValue(s.value.count);
                let bytes = new BytesValue(s.value.bytes);
                let elapsed = TimeValue.fromSecondsNanos(s.value.elapsed.secs, s.value.elapsed.nanos);
                // Kept as elapsed/count so that a region's latency weighs each node by the
                // number of accesses it served.
                let avg_latency = new RatioValue(elapsed, count.value);
                return [
                    new Measurement(metric_id + ".count", Option.some(count), AggregationMode.Sum),
                    new Measurement(metric_id + ".bytes", Option.some(bytes), AggregationMode.Sum),
                    new Measurement(metric_id + ".elapsed", Option.some(elapsed), AggregationMode.Sum),
                    new Measurement(metric_id + ".avg_latency", Option.some(avg_latency), AggregationMode.WeightedRatio)
                ];
            }
            case "stats": {
                let s = metric.value as StatsMetricValue;
                let count = CountValue.fromCountMetric(s.batches_count);
                let max_size = CountValue.fromCountMetric(s.max_records_count);
                let min_size = CountValue.fromCountMetric(s.min_records_count);
                let record_count = CountValue.fromCountMetric(s.total_records_count);
                // The profile reports the average too, but as records/batches we can aggregate it correctly
                let avg_size = new RatioValue(record_count, count.value);
                return [
                    new Measurement(metric_id + ".count", Option.some(count), AggregationMode.Sum),
                    new Measurement(metric_id + ".avg_size", Option.some(avg_size), AggregationMode.WeightedRatio),
                    new Measurement(metric_id + ".max_size", Option.some(max_size), AggregationMode.Max),
                    new Measurement(metric_id + ".min_size", Option.some(min_size), AggregationMode.Min),
                    new Measurement(metric_id + ".record_count", Option.some(record_count), AggregationMode.Sum)
                ];
            }
            case "id": { // persistent_id
                let s = metric.value as StringMetricValue;
                let str = StringValue.fromString(s.value);
                return [new Measurement(metric_id, Option.some(str), AggregationMode.CommonValue)];
            }
            case "percent": {
                let s = metric.value as PercentMetricValue;
                let perc = PercentValue.fromPercentMetric(s);
                const mode = metric.metric_id === Measurement.RUNTIME_PERCENT
                    ? AggregationMode.CommonDenominator
                    : AggregationMode.WeightedRatio;
                return [new Measurement(metric_id, Option.some(perc), mode)];
            }
            case "seconds": {
                if (metric.value === undefined) {
                    return []
                }
                let s = metric.value as DurationMetricValue;
                let duration = TimeValue.fromDurationMetric(s);
                // Durations measure a node's own work on a worker's thread and add up, except
                // for the circuit's elapsed time, which is one wall clock the profile repeats
                // for every node and worker.
                const mode = metric.metric_id === Measurement.RUNTIME_ELAPSED
                    ? AggregationMode.Max
                    : AggregationMode.Sum;
                return [new Measurement(metric_id, Option.some(duration), mode)];
            }
            case "occupancy": {
                let s = metric.value as OccupancyValue;
                let max = BytesValue.fromBytesMetric(s.max);
                let used = BytesValue.fromBytesMetric(s.used);
                return [
                    new Measurement(metric_id + ".max", Option.some(max), AggregationMode.Max),
                    new Measurement(metric_id + ".used", Option.some(used), AggregationMode.Max)
                ];
            }
            case "bounds": {
                // retainment_bounds
                let s = metric.value as RetainmentValue;
                let object: Array<string> = [];
                let result = [];
                if (s.key instanceof Array) {
                    for (const keyVal of s.key) {
                        if (keyVal.value !== "None") {
                            object.push(keyVal.value);
                        }
                    }
                } else {
                    let keyValue = (s.key as SerializedStringValue).value;
                    if (keyValue !== "None") {
                        object.push(keyValue);
                    }
                }
                if (object.length !== 0) {
                    let str = object.join();
                    result.push(new Measurement(metric_id + ".key_bounds",
                        Option.some(new StringValue(str)), AggregationMode.CommonValue));
                }

                object = [];
                if (s.value instanceof Array) {
                    for (const valVal of s.value) {
                        if (valVal.value !== "None") {
                            object.push(valVal.value);
                        }
                    }
                } else {
                    let valValue = (s.value as SerializedStringValue).value;
                    if (valValue !== "None") {
                        object.push(valValue);
                    }
                }
                if (object.length !== 0) {
                    let str = object.join();
                    result.push(new Measurement(metric_id + ".value_bounds",
                        Option.some(new StringValue(str)), AggregationMode.CommonValue));
                }

                return result;
            }
            case "merges": {
                let s = metric.value as MergesMetricValue;
                let batches = CountValue.fromCountMetric(s.batches);
                let merges = CountValue.fromCountMetric(s.merges);
                let steps = CountValue.fromCountMetric(s.steps);
                let result = [];
                // The profile reports the per-step averages already divided, so multiplying by
                // the step count recovers the totals; a region then weighs each node by the
                // steps it took.
                for (const [field, average] of [
                    ["avg_step_seconds", s.avg_step_seconds],
                    ["avg_step_cpu_seconds", s.avg_step_cpu_seconds]] as const) {
                    if (average === undefined) {
                        continue;
                    }
                    const total = TimeValue.fromDurationMetric(average).scale(steps.value);
                    result.push(new Measurement(metric_id + "." + field,
                        Option.some(new RatioValue(total, steps.value)),
                        AggregationMode.WeightedRatio));
                }
                result.push(
                    new Measurement(metric_id + ".batches", Option.some(batches), AggregationMode.Sum),
                    new Measurement(metric_id + ".merges", Option.some(merges), AggregationMode.Sum),
                    new Measurement(metric_id + ".steps", Option.some(steps), AggregationMode.Sum),
                );
                return result;
            }
            case "policy": {
                let s = metric.value as StringMetricValue;
                let str = StringValue.fromString(s.value);
                return [new Measurement(metric_id, Option.some(str), AggregationMode.CommonValue)];
            }
        }
        return [];
    }

    /** Parse a JSON object with the specified label into zero or more measurements.
     * TODO: remove this function once legacy representations are no longer supported. */
    static parseLegacyValues(json: JsonMeasurement): Array<Measurement> {
        let prefix = json[0] as string;
        let value = json.slice(1);
        let result: Array<Measurement> = new Array();
        switch (prefix) {
            case "output batches":
            case "input batches":
                if (Array.isArray(value[0])) {
                    // Empty object was serialized as an empty array
                    break
                }
                let entries = value[0].entries;
                for (const e of entries) {
                    // A slash, which is how these metrics are spelled in `parseLegacyPropertyValue`
                    // and in `legacyMeasurementCategory`.  A dot here left every one of them
                    // unparsed and uncategorized.
                    result.push(Measurement.fromJson(prefix + "/", e));
                }
                break;
            case "foreground cache misses":
            case "foreground cache hits":
            case "background cache misses":
            case "background cache hits":
                let count = value[0].count;
                result.push(new Measurement(prefix + ".count", Option.some(new CountValue(count)), AggregationMode.Sum));
                let bytes = value[0].bytes;
                result.push(new Measurement(prefix + ".bytes", Option.some(new CountValue(bytes)), AggregationMode.Sum));
                let elapsed = value[0].elapsed;
                result.push(new Measurement(prefix + ".elapsed",
                    Option.some(TimeValue.fromSecondsNanos(elapsed.secs, elapsed.nanos)), AggregationMode.Sum));
                break;
            default:
                result.push(Measurement.fromJson("", json));
                break;
        }
        return result;
    }

    static unknownProperties: Set<string> = new Set();

    private static parseLegacyPropertyValue(prop: string, value: Array<any>): Option<LegacyReading> {
        switch (prop) {
            case "time%":
                // Every node divides its own runtime by the same circuit-wide total.
                return Measurement.tagged(new PercentValue(value[0][0], value[0][1]),
                    AggregationMode.CommonDenominator);
            case "merge reduction":
            case "output redundancy":
            case "background cache hit rate":
            case "foreground cache hit rate":
            case "Bloom filter hit rate":
                return Measurement.tagged(new PercentValue(value[0][0], value[0][1]),
                    AggregationMode.WeightedRatio);
            case "input batches/avg size":
            case "output batches/avg size":
                // The legacy format reports the average pre-divided and does not say over how
                // many batches, so each node counts once: a region reads as the mean of the
                // averages of the nodes it contains.
                return Measurement.tagged(new RatioValue(new CountValue(value[0]), 1),
                    AggregationMode.WeightedRatio);
            case "input batches/min size":
            case "output batches/min size":
                return Measurement.tagged(new CountValue(value[0]), AggregationMode.Min);
            case "input batches/max size":
            case "output batches/max size":
                return Measurement.tagged(new CountValue(value[0]), AggregationMode.Max);
            case "Bloom filter size":
            case "Bloom filter bits/key":
            case "Bloom filter hits":
            case "Bloom filter misses":
            case "total size":
            case "invocations":
            case "allocated bytes":
            case "used bytes":
            case "shared bytes":
            case "batches":
            case "storage size":
            case "merging batches":
            case "merging size":
            case "allocations":
            case "left inputs":
            case "right inputs":
            case "computed outputs":
            case "inputs":
            case "steps":
            case "input batches/batches":
            case "input batches/total records":
            case "output batches/batches":
            case "output batches/total records":
            case "integral records to repartition":
            case "rebalancings":
            case "local shard size":
            case "accumulator records to repartition":
                return Measurement.tagged(new CountValue(value[0]), AggregationMode.Sum);
            case "runtime_elapsed":
                // The legacy name of Measurement.RUNTIME_ELAPSED: one wall clock, repeated.
                return Measurement.tagged(
                    TimeValue.fromSecondsNanos(value[0].secs, value[0].nanos),
                    AggregationMode.Max);
            case "wait_time":
            case "exchange_wait_time":
            case "merge backpressure wait":
            case "time":
            case "total_idle_time":
            case "total_runtime":
            case "total rebalancing time":
            case "in-progress rebalancing time":
                return Measurement.tagged(
                    TimeValue.fromSecondsNanos(value[0].secs, value[0].nanos), AggregationMode.Sum);
            case "persistent_id":
            case "foreground cache occupancy":
            case "background cache occupancy":
            case "balancer policy":
            case "slot 0 loose":
            case "slot 1 loose":
            case "slot 2 loose":
            case "slot 3 loose":
            case "slot 4 loose":
            case "slot 0 completed":
            case "slot 1 completed":
            case "slot 2 completed":
            case "slot 3 completed":
            case "slot 4 completed":
            case "slot 0 merging":
            case "slot 1 merging":
            case "slot 2 merging":
            case "slot 3 merging":
            case "slot 4 merging":
            case "balancer.policy":
                return Measurement.tagged(new StringValue(value[0]), AggregationMode.CommonValue);
            case "rebalancing in progress":
                return Measurement.tagged(new BooleanValue(value[0]), AggregationMode.Or);
            case "bounds":
            case "mir_node":
            case "key distribution":
                // TODO: currently ignoring some complex properties that we don't know how to convert to scalars
                return Option.none();
            default:
                // We don't know this kind of property, we should probably analyze it.
                if (!Measurement.unknownProperties.has(prop)) {
                    console.log("Unknown property " + prop);
                    Measurement.unknownProperties.add(prop);
                }
                return Option.none();
        }
    }
}

/** How one metric's readings are placed on screen. */
export interface MetricScale {
    /** Range of the individual worker readings, which colors the per-worker bars and the node
     * highlighting. */
    readonly range: NumericRange;
    /** Largest total a drawn node reports, which shades the totals.  Absent for the metrics that
     * do not add up, which have no total to shade. */
    readonly maximum?: number;
}

/** The scales the rendering colors against, by metric, over the nodes currently drawn. */
export type DisplayScales = Map<string, MetricScale>;

/** A total as a percentage of the largest total on display, clamped to [0, 100]: 100 for the
 * node holding the most, near zero for one holding a negligible share.  Zero when there is
 * nothing on display to compare against. */
export function totalShare(total: PropertyValue, largest: number | undefined): number {
    const value = total.getNumericValue();
    if (largest === undefined || largest <= 0 || value.isNone()) {
        return 0;
    }
    return Math.max(0, Math.min(100, 100 * value.unwrap() / largest));
}

/** Shares for the totals of the toplevel node, which stands for the whole circuit.  It holds the
 * largest total of every metric by construction, so `totalShare` would place all of them at 100.
 * These place each total against the others of its category -- the group it is displayed
 * alongside -- on a log scale, since a category's totals routinely span a byte count in the
 * billions beside a batch count in the hundreds. */
export function categoryShares(totals: Map<string, PropertyValue>): Map<string, number> {
    const magnitudes = new Map<string, number>();
    const largest = new Map<string, number>();
    for (const [metric, total] of totals) {
        const value = total.getNumericValue();
        if (value.isNone()) {
            continue;
        }
        const magnitude = Math.max(0, value.unwrap());
        magnitudes.set(metric, magnitude);
        const category = measurementCategory(metric);
        largest.set(category, Math.max(largest.get(category) ?? 0, magnitude));
    }
    const shares = new Map<string, number>();
    for (const [metric, magnitude] of magnitudes) {
        const top = largest.get(measurementCategory(metric))!;
        shares.set(metric, top > 0 ? 100 * Math.log1p(magnitude) / Math.log1p(top) : 0);
    }
    return shares;
}

/** A node, its operation, and the (maximum) value of a metric for that node.  The actual metric
 * represented is not part of this data structure */
export class NodeAndMetric {
    constructor(
        public readonly nodeId: string,
        public readonly label: string,
        public readonly operation: string,
        /** Value between 0 and 100% */
        public readonly normalizedValue: number) { }
}

/** A set of measurements for a single circuit graph node and many workers.
 * Only stores numeric values! */
class Measurements {
    readonly measurements: OMap<string, Array<PropertyValue>> = new OMap();
    // How each metric folds over the nodes of a region; see `append`.
    private readonly aggregations: OMap<string, AggregationMode> = new OMap();

    constructor(private worker_count: number) { }

    add(worker: number, m: Measurement) {
        if (m.value.isNone()) return;  // Ignore unknown properties.
        if (m.property === "persistent_id") {
            return;
        }
        this.aggregations.set(m.property, m.aggregation);
        let meas = this.measurements.get(m.property);
        let arr: Array<PropertyValue>;
        if (meas.isNone()) {
            arr = [];
            for (let i = 0; i < this.worker_count; i++)
                arr[i] = new MissingValue();
            this.measurements.set(m.property, arr);
        } else {
            arr = meas.unwrap();
        }
        arr[worker] = m.value.unwrap();
    }

    getMetrics(): Iterable<string> {
        let result = this.measurements.keys();
        if (MetricDescriptions.known()) {
            let data = [...result];
            data.sort((c1, c2) => MetricDescriptions.getMetricIndex(c1) - MetricDescriptions.getMetricIndex(c2));
            return data;
        }
        return result;
    }

    /** How the metric named `key` is aggregated, if this set holds a reading for it. */
    aggregationFor(key: string): Option<AggregationMode> {
        return this.aggregations.get(key);
    }

    /** How the metric named `key` is aggregated. */
    private aggregationOf(key: string): AggregationMode {
        const mode = this.aggregationFor(key);
        if (mode.isNone()) {
            fail("No aggregation mode recorded for metric " + key);
        }
        return mode.unwrap();
    }

    /** Add all of `other`'s values to this set. */
    append(other: Measurements) {
        for (const [key, values] of other.measurements.entries()) {
            let existing = this.measurements.get(key);
            if (existing.isNone()) {
                this.measurements.set(key, [...values]);
                this.aggregations.set(key, other.aggregationOf(key));
            } else {
                let arr = existing.unwrap();
                assert(arr.length === values.length, "Mismatched measurement lengths");
                const mode = this.aggregationOf(key);
                for (let i = 0; i < values.length; i++) {
                    arr[i] = arr[i]!.aggregate(values[i]!, mode);
                }
            }
        }
    }

    toString(): string {
        let result = "";
        for (const [key, value] of this.measurements.entries()) {
            if (result !== "")
                result += "\n";
            result += key + " => " + value.toString();
        }
        return result;
    }
}

/** A simple circuit node corresponds to a primitive DBSP operator.
 * ComplexNodes are really regions in the profile comprising multiple other nodes. */
export class SimpleNode implements JsonSimpleCircuitNode {
    // One measurement set per worker
    readonly measurements: Measurements;
    operation: string;
    // Source position of the Rust code in the DBSP library.
    readonly dbspSourcePosition: Option<string>;
    sourcePositions: SourcePositionRanges;
    persistentId: Option<string>;

    constructor(readonly id: NodeId, readonly label: string, worker_count: number) {
        this.measurements = new Measurements(worker_count);
        let parts = label.split('@');
        this.operation = parts[0]!;
        this.dbspSourcePosition = parts[1] ? Option.some(parts[1]) : Option.none();
        this.sourcePositions = SourcePositionRanges.empty();
        this.persistentId = Option.none();
    }

    getChildren(): Array<NodeId> {
        return [];
    }

    setPersistentId(id: string) {
        this.persistentId = Option.some(id);
    }

    addMeasurement(m: Measurement, worker: number) {
        this.measurements.add(worker, m);
    }

    getMeasurements(property: string): Array<PropertyValue> {
        return this.measurements.measurements.get(property).unwrapOr([]);
    }

    /** The metric's readings from `values` added up, for metrics that add up: counts, byte
     * sizes and durations.  None for the others -- a total of ratios, of minima, of maxima, of
     * flags or of settings states nothing.  `values` are this node's readings for the workers
     * the caller is showing, so the total covers the same workers as the display. */
    totalOf(property: string, values: Array<PropertyValue>): Option<PropertyValue> {
        const mode = this.measurements.aggregationFor(property);
        if (mode.isNone() || mode.unwrap() !== AggregationMode.Sum) {
            return Option.none();
        }
        let total: PropertyValue = MissingValue.INSTANCE;
        for (const value of values) {
            total = total.aggregate(value, AggregationMode.Sum);
        }
        return total instanceof MissingValue ? Option.none() : Option.some(total);
    }

    // Add all the values from `measurements` into this node's measurements.
    append(measurements: Measurements) {
        this.measurements.append(measurements);
    }

    setSourcePositions(positions: SourcePositionRanges) {
        this.sourcePositions = positions;
    }
}

/** A complex node has a list of children nodes.  Note that the class extends SimpleNode. */
export class ComplexNode extends SimpleNode {
    children: Array<NodeId>;
    depth: number = 0;
    // Number of primitive operators anywhere inside this region.
    leafCount: number = 0;
    // Names of tables and views of descendant nodes.
    readonly containedNames: Array<string> = [];

    constructor(id: NodeId, label: string, worker_count: number) {
        super(id, label, worker_count);
        this.children = [];
    }

    /** Label to display when the node is drawn collapsed:
     * the operation plus the names of the tables and views hidden inside. */
    collapsedOperation(): string {
        if (this.containedNames.length === 0) {
            return this.operation;
        }
        return this.operation + " " + this.containedNames.join(", ");
    }

    addChild(node: SimpleNode) {
        this.children.push(node.id);
    }

    appendMeasurements(node: SimpleNode) {
        this.measurements.append(node.measurements);
    }

    setDepth(depth: number) {
        this.depth = depth;
    }

    setLeafCount(count: number) {
        this.leafCount = count;
    }

    override getChildren(): Array<NodeId> {
        return this.children;
    }
}

/** An edge in the profile graph. */
export class ProfileEdge {
    constructor(readonly source: NodeId, readonly target: NodeId, readonly back: boolean) { }

    toString(): string {
        return this.source + "->" + this.target;
    }
}

export class CircuitProfile {
    public readonly simpleNodes: OMap<NodeId, SimpleNode> = new OMap();
    public readonly edges: Array<ProfileEdge> = new Array();
    public readonly complexNodes: OMap<NodeId, ComplexNode> = new OMap();
    // Maps each node id to it's immediate parent id.
    public readonly parents: OMap<NodeId, NodeId> = new OMap();
    // Names of all worker threads
    private workerNames: Array<number> = new Array();
    // For each node, how many consumers it feeds; see `computeConsumers`.
    private readonly consumers: Map<NodeId, number> = new Map();
    // Index nodes by their persistent IDs
    readonly byPersistentId: OMap<string, SimpleNode> = new OMap();
    // Index nodes by table or view name (lowercase); filled from the dataflow graph.
    readonly byName: OMap<string, SimpleNode> = new OMap();
    // Source information; only available if the dataflow information is provided.
    sources: Option<Sources> = Option.none();

    /** True if this id corresponds to the toplevel profile graph node.
     * Profile graphs are always a single node containing everything else inside.
     * That node is pretty much ignored everywhere else in this code after parsing. */
    isTop(node: NodeId): boolean {
        return node === this.rootNodeId;
    }

    addNode(n: JsonSimpleNodeWrapper | JsonClusterWrapper, parent: Option<NodeId>) {
        if ('Simple' in n) {
            let node = n.Simple;
            this.simpleNodes.set(node.id, new SimpleNode(node.id, node.label, this.worker_count));
            if (parent.isSome() && !this.isTop(parent.unwrap())) {
                this.parents.set(node.id, parent.unwrap());
            }
        } else {
            let node = n.Cluster;
            this.complexNodes.set(node.id, new ComplexNode(node.id, node.label, this.worker_count));
            for (const child of node.nodes) {
                this.addNode(child, Option.some(node.id));
            }
            if (parent.isSome() && !this.isTop(parent.unwrap())) {
                this.parents.set(node.id, parent.unwrap());
            }
        }
    }

    // The profile graph lies about some nodes, by reverting the edges between them
    // These are the nodes we are looking for and "correcting" while parsing the graph.
    static readonly Z1_TRACE = "Z1 (trace)";
    static readonly Z1_TRACE_OUTPUT = "Z1 (trace) (output)";
    static readonly Z1 = "Z^-1";
    static readonly Z1_OUTPUT = "Z^-1 (output)";
    // Name of the property that holds the persistent ID.
    // In the profile graph this is represented in all workers (if present)
    public static readonly PERSISTENT_ID = "persistent_id";

    // Parse the MIR node of a dataflow graph representation.
    processMirNode(mir: MirNode) {
        let persistent_id = mir.persistent_id;
        if (!persistent_id) return;
        let profileNode = this.byPersistentId.get(persistent_id);
        // This can happen for some Z nodes in recursive components
        if (profileNode.isNone()) return;
        let n = profileNode.unwrap();
        // Older dataflow graphs omit `table`/`view` instead of emitting nulls.
        const name = mir.table ?? mir.view ?? null;
        if (name !== null) {
            n.operation += " " + name;
            this.byName.set(name.toLowerCase(), n);
            // Ancestors display the contained names when collapsed
            let parent = this.parents.get(n.id);
            while (parent.isSome()) {
                const complex = this.complexNodes.get(parent.unwrap()).unwrap();
                if (!complex.containedNames.includes(name)) {
                    complex.containedNames.push(name);
                }
                parent = this.parents.get(parent.unwrap());
            }
        }

        n.setSourcePositions(new SourcePositionRanges(
            mir.positions.map(p => new SourcePositionRange(p))));
    }

    /** Find the node of an input table or output view by name.
     * The match is case-insensitive; an exact match wins over a substring match. */
    findByName(name: string): Option<SimpleNode> {
        const key = name.toLowerCase();
        const exact = this.byName.get(key);
        if (exact.isSome()) {
            return exact;
        }
        for (const [n, node] of this.byName.entries()) {
            if (n.includes(key)) {
                return Option.some(node);
            }
        }
        return Option.none();
    }

    /** The given nodes ranked by `metric`, largest first.
     * A node is judged by the metric's total over its workers where the metric adds up, and by
     * its largest worker reading otherwise: a node busy on every worker outranks one busy on a
     * single worker, which ranking by the largest reading alone cannot express.  Nodes with no
     * reading for the metric are left out. */
    rankNodes(metric: string, nodes: Array<{ id: NodeId, label: string }>): Array<NodeAndMetric> {
        // The nodes are placed against each other, so collect the readings before scaling them.
        let ranked: Array<{ id: NodeId, label: string, value: PropertyValue, numeric: number }> = [];
        for (const node of nodes) {
            const profileNode = this.getNode(node.id);
            if (profileNode.isNone()) { continue; }
            const values = profileNode.unwrap().getMeasurements(metric);
            const total = profileNode.unwrap().totalOf(metric, values);
            let chosen: PropertyValue | null = null;
            let numeric: number | null = null;
            if (total.isSome()) {
                chosen = total.unwrap();
                numeric = chosen.getNumericValue().unwrapOr(0);
            } else {
                for (const value of values) {
                    const num = value.getNumericValue();
                    if (num.isNone()) { continue; }
                    if (numeric === null || num.unwrap() > numeric) {
                        numeric = num.unwrap();
                        chosen = value;
                    }
                }
            }
            if (numeric === null) { continue; }
            ranked.push({ id: node.id, label: node.label, value: chosen!, numeric });
        }
        // Each node is placed against the others in the list, whichever measure was used: a
        // total is larger than any single worker's reading, so the two do not share a scale.
        const range = NumericRange.getRange(ranked.map(r => r.numeric));
        if (range.isEmpty()) {
            return [];
        }
        const result = ranked.map(r => new NodeAndMetric(
            r.id, r.value.toString(), r.label, range.isPoint() ? 0 : range.percents(r.numeric)));
        result.sort((a, b) => b.normalizedValue - a.normalizedValue);
        return result;
    }

    /** The node itself, then the regions containing it, innermost first. */
    private enclosing(node: NodeId): Array<NodeId> {
        const chain = [node];
        let parent = this.parents.get(node);
        while (parent.isSome()) {
            chain.push(parent.unwrap());
            parent = this.parents.get(parent.unwrap());
        }
        return chain;
    }

    /** How many edges are leaving `node`.  Since this is a multi-graph, there
      * can be multiple edges between a pair of nodes. */
    consumerCount(node: NodeId): number {
        return this.consumers.get(node) ?? 0;
    }

    /** Fill in `consumers`. */
    private computeConsumers() {
        this.consumers.clear();
        for (const edge of this.edges) {
            const targetRegions = this.enclosing(edge.target);
            // Account the edge for its source node AND all its ancestors
            for (const ancestor of this.enclosing(edge.source)) {
                // An edge that has both source and destination in the same region is not counted.
                if (targetRegions.includes(ancestor)) {
                    break;
                }
                this.consumers.set(ancestor, this.consumerCount(ancestor) + 1);
            }
        }
    }

    // Get the topmost parent of a node which is not the toplevel graph node.
    getTopParent(node: NodeId): NodeId {
        while (this.parents.has(node)) {
            node = this.parents.get(node).unwrap();
        }
        return node;
    }

    // TODO: memoize depths for faster computation
    computeDepth(nodeId: NodeId): number {
        let node = this.getNode(nodeId);
        let depth = 0;
        if (!node.isNone()) {
            for (const child of node.unwrap().getChildren()) {
                depth = Math.max(depth, this.computeDepth(child) + 1);
            }
        }
        return depth;
    }

    // Set the dataflow graph information of a profile graph.
    setDataflow(dataflow?: Dataflow, programCode?: string[]) {
        // Add information from the program dataflow generated by the SQL compiler.
        const sources = dataflow?.sources ?? programCode;
        if (sources) {
            this.sources = Option.some(new Sources(sources));
        }

        if (!dataflow) {
            return;
        }

        let mir = dataflow.mir;
        for (const [_, info] of Object.entries(mir)) {
            if (info.operation === "nested") {
                for (const [key, mir] of Object.entries(info)) {
                    if (["calcite", "table", "view", "inputs", "outputs", "persistent_id", "positions"].includes(key)) {
                        continue;
                    }
                    this.processMirNode(mir);
                }
            } else {
                let mir: MirNode = info as MirNode;
                this.processMirNode(mir);
            }
        }

        // Adjust source positions
        for (const node of this.simpleNodes.values()) {
            const parent = this.parents.get(node.id);
            if (parent.isSome()) {
                // If parent is toplevel graph, it's not in the graph
                const complex = this.complexNodes.get(parent.unwrap()).unwrap();
                complex.sourcePositions.append(node.sourcePositions);
            }
        }
        // And adjust the parents of the parents, etc.
        for (const node of this.getSortedComplexNodes()) {
            const parent = this.parents.get(node.id);
            if (parent.isSome()) {
                const complex = this.complexNodes.get(parent.unwrap()).unwrap();
                complex.sourcePositions.append(node.sourcePositions);
            }
        }
    }

    // Return the complex nodes in order of increasing depth
    getSortedComplexNodes(): Array<ComplexNode> {
        let result = [... this.complexNodes.values()];
        result.sort((n1, n2) => n1.depth - n2.depth);
        return result;
    }

    addEdge(e: JsonCircuitEdge) {
        // Some edges are reversed in the profile.
        // For example, between Z1 (trace) and Z1 (trace) (output)
        let from = e.from_node;
        let to = e.to_node;
        let source = this.getNode(from);
        let target = this.getNode(to);
        let back = false;
        if (source.isSome() && target.isSome()) {
            let sourceLabel = source.unwrap().label;
            let targetLabel = target.unwrap().label;
            // Reverse the edge if it's between Z1 (trace) and Z1 (trace) (output)
            // or between Z1_OUTPUT and Z1
            if ((sourceLabel.includes(CircuitProfile.Z1_TRACE_OUTPUT) && targetLabel.includes(CircuitProfile.Z1_TRACE)) ||
                (sourceLabel.includes(CircuitProfile.Z1_OUTPUT) && targetLabel === CircuitProfile.Z1)) {
                let tmp = from;
                from = to;
                to = tmp;
                back = true;
            }
        }

        this.edges.push(new ProfileEdge(from, to, back));
    }

    getWorkerNames(): Array<number> {
        return this.workerNames;
    }

    getNode(id: NodeId): Option<SimpleNode> {
        if (this.simpleNodes.has(id))
            return this.simpleNodes.get(id);
        return this.complexNodes.get(id);
    }

    /**
     * Get all source code position ranges for a given node ID.
     *
     * A node can have multiple source position ranges when a single DBSP operator
     * corresponds to multiple SQL fragments (e.g., a join referencing tables defined
     * in different parts of the SQL).
     *
     * @param id - The node ID to look up
     * @returns Array of SourcePositionRange objects, or empty array if,
     *          - Node doesn't exist
     *          - Node has no source position information
     */
    // This method is in CircuitProfile rather than Visualizer because CircuitProfile
    // owns both the node data (simpleNodes/complexNodes) and the source data (sources).
    getSourceRanges(id: NodeId): Array<SourcePositionRange> {
        const node = this.getNode(id);
        if (node.isNone()) {
            return [];
        }

        return node.unwrap().sourcePositions.positions;
    }

    /**
     * Get the first source code position range for a given node ID.
     *
     * Convenience method that returns the first (primary) range from getSourceRanges(),
     * typically used for simple navigation purposes.
     *
     * @param id - The node ID to look up
     * @returns Option containing the first SourcePositionRange, or none if no ranges exist
     */
    getFirstSourceRange(id: NodeId): Option<SourcePositionRange> {
        const ranges = this.getSourceRanges(id);
        if (ranges.length === 0) {
            return Option.none();
        }
        return Option.some(ranges[0]!);
    }

    /** @param rootNodeId Id of the toplevel graph node, taken from the parsed profile. */
    constructor(readonly worker_count: number, readonly rootNodeId: NodeId) { }

    /** The scales the display colors against, taken over the nodes it draws: an expanded region
     * is drawn as the nodes inside it, so those count and the region does not, while a collapsed
     * region stands for everything inside it and counts in their place.  `visible` selects the
     * workers on display, so the scales cover the readings that are actually shown.
     *
     * Both scales come from one pass, since they walk the same readings. */
    displayScales(nodes: Array<NodeId>,
        visible: (values: Array<PropertyValue>) => Array<PropertyValue>): DisplayScales {
        const scales: DisplayScales = new Map();
        for (const id of nodes) {
            const found = this.getNode(id);
            if (found.isNone()) {
                continue;
            }
            const node = found.unwrap();
            for (const metric of node.measurements.getMetrics()) {
                const shown = visible(node.getMeasurements(metric));
                const numbers = shown.map(v => v.getNumericValue())
                    .filter(v => v.isSome()).map(v => v.unwrap());
                const previous = scales.get(metric);
                const readings = NumericRange.getRange(numbers);
                const range = previous === undefined
                    ? readings
                    : previous.range.union(readings);

                let maximum = previous?.maximum;
                const total = node.totalOf(metric, shown).map(t => t.getNumericValue());
                if (total.isSome() && total.unwrap().isSome()) {
                    const value = total.unwrap().unwrap();
                    maximum = maximum === undefined ? value : Math.max(maximum, value);
                }
                scales.set(metric, maximum === undefined ? { range } : { range, maximum });
            }
        }
        return scales;
    }

    // Decode the data in a worker profile; return a map from nodeId to an array of measurements for that node
    private decodeWorkerProfile(json: JsonWorkerProfile['metadata']): Map<NodeId, Array<Measurement>> {
        let metadata = new Map<NodeId, Array<Measurement>>();
        for (const [nodeId, data] of Object.entries(json)) {
            let parsed: Array<Measurement> = [];
            for (const datum of data) {
                let measurements = Measurement.parseValues(datum);
                for (const m of measurements) {
                    parsed.push(m);
                }
            }
            metadata.set(nodeId, parsed);
        }
        return metadata;
    }

    // Decoder for legacy profile format, to be removed
    private decodeLegacyWorkerProfile(json: LegacyJsonWorkerProfile['metadata']): Map<NodeId, Array<Measurement>> {
        let metadata = new Map<NodeId, Array<Measurement>>();
        for (const [nodeId, data] of Object.entries(json)) {
            let parsed: Array<Measurement> = [];
            for (const datum of data.entries) {
                let measurements = Measurement.parseLegacyValues(datum);
                for (const m of measurements) {
                    parsed.push(m);
                }
            }
            metadata.set(nodeId, parsed);
        }
        return metadata;
    }

    /** Create a CircuitProfile from the JSON serialization */
    static fromJson(json: JsonProfiles) {
        // For some reason, the profiles generated in the new format sometimes do not include `metrics` field.
        // With this simple heuristic we can detect and still parse those profiles, but we should investigate why this happens and fix it.
        // Here, we check if the first profile measurement contains a metric_id field, which is a required field in the new format and is absent in the old format.
        // TODO: remove this block once legacy representations are no longer supported.
        if (!('metrics' in json) && (Object.values(json.worker_profiles[0]?.metadata ?? {}) as any)?.[0]?.[0]?.['metric_id']) {
            (json as any).metrics = [];
        }

        const isNewProfile = 'metrics' in json;
        if (isNewProfile) {
            MetricDescriptions.setMetricDescriptions(json.metrics);
        }

        let worker_count = json.worker_profiles.length;
        // Decode the graph structure and create the nodes.
        // The graph itself is always a complex node.
        let rootNodeId = json.graph.nodes.id;
        let result = new CircuitProfile(worker_count, rootNodeId);
        result.complexNodes.set(rootNodeId,
            new ComplexNode(rootNodeId, json.graph.nodes.label, worker_count));
        for (const nodeWrapper of json.graph.nodes.nodes) {
            // Ignore top-level graph region
            result.addNode(nodeWrapper, Option.none());
        }
        for (const edge of json.graph.edges) {
            result.addEdge(edge);
        }

        const decodedProfiles = isNewProfile ?
            json.worker_profiles.entries().map(([index, workerProfile]) => tuple(index, result.decodeWorkerProfile(workerProfile.metadata))) :
            json.worker_profiles.entries().map(([index, workerProfile]) => tuple(index, result.decodeLegacyWorkerProfile(workerProfile.metadata)))

        // Decode the profile information and attach to the nodes.
        for (const [index, decoded] of decodedProfiles
        ) {
            for (const [node, measurements] of decoded.entries()) {
                let n: SimpleNode;
                if (result.simpleNodes.has(node)) {
                    n = result.simpleNodes.get(node).unwrap();
                    for (const m of measurements) {
                        n.addMeasurement(m, index);
                        if (m.property === CircuitProfile.PERSISTENT_ID && m.value.isSome()) {
                            let pid = m.value.unwrap().getStringValue();
                            result.byPersistentId.set(pid, n);
                            n.setPersistentId(pid);
                        }
                    }
                } else if (result.complexNodes.has(node)) {
                    // Ignore measurements for complex nodes, except the root node, which has some special attributes
                    if (node === rootNodeId) {
                        n = result.complexNodes.get(node).unwrap();
                        for (const m of measurements) {
                            n.addMeasurement(m, index);
                        }
                    }
                } else {
                    fail("Node not found " + node);
                }
            }
        }

        result.workerNames = Array.from({ length: json.worker_profiles.length }, (_, i) => i);
        // Merge Z1 (trace) nodes; they are artificially split in the profile into two halves each.
        result.fixZ1Nodes();
        // After fixZ1Nodes, which rewrites edges and deletes the nodes it merges.
        result.computeConsumers();

        // Register children
        for (const node of [...result.simpleNodes.values(), ...result.complexNodes.values()]) {
            const parent = result.parents.get(node.id);
            if (parent.isSome()) {
                // If parent is toplevel graph, it is None
                const complex = result.complexNodes.get(parent.unwrap()).unwrap();
                complex.addChild(node);
            }
        }

        // Compute and save depths
        for (const node of result.complexNodes.values()) {
            node.setDepth(result.computeDepth(node.id));
        }

        // Assign to every complex node the "sum" of the children's measurements,
        // and the number of primitive operators inside it.
        // `depth` is the height above the leaves, so increasing depth visits a
        // region after its subregions, and their counts are final when it reads them.
        for (const complex of result.getSortedComplexNodes()) {
            let leaves = 0;
            for (const child of complex.children) {
                const node = result.getNode(child).unwrap();
                complex.appendMeasurements(node);
                leaves += node instanceof ComplexNode ? node.leafCount : 1;
            }
            complex.setLeafCount(leaves);
        }

        return {
            profile: result,
            rootNodeId
        };
    }

    fixZ1Nodes() {
        // A Z1 node is represented as a "Z1 (trace)" node followed by a "Z1 (trace) (output)" node.
        // We have already flipped the edges while parsing so that there's a back-edge from Z1 to Z1 (output).
        // Now we remove the Z1 node, redirect all its incoming edges to Z1 (output),
        // and merge the measurements into the Z1 (output).
        const edges = new Array<ProfileEdge>();

        let backEdges = this.edges.filter(e => e.back);
        let toReplace = new Map<string, string>(backEdges.map(e => [e.source, e.target]));

        for (const edge of this.edges) {
            if (edge.back) {
                let sourceNode = this.simpleNodes.get(edge.source).unwrap();
                let targetNode = this.simpleNodes.get(edge.target).unwrap();
                targetNode.append(sourceNode.measurements);
                assert(toReplace.has(edge.source), "Expected to delete node " + edge.source);
                this.simpleNodes.delete(edge.source);
            } else {
                if (toReplace.has(edge.target)) {
                    // Redirect edge to the target of the back edge.
                    let redirect = new ProfileEdge(edge.source, toReplace.get(edge.target)!, true);
                    edges.push(redirect);
                } else {
                    edges.push(edge);
                }
            }
        }
        this.edges.length = 0;
        for (const edge of edges) {
            this.edges.push(edge);
        }
    }
}

