#!/bin/bash
# Create a symlink from `.git/hooks/pre-push` to this script to run the checks below
# before pushing changes to github.  This will avoid CI failures due to clippy
# lints and formatting issues.

echo "Checking Rust rules prior to push.  To run this check by hand invoke 'tools/pre-push'"

set -ex

if [ $# -gt 0 ]; then
    cargo fmt -- --config imports_granularity=Crate
else
    cargo fmt -- --check --config format_code_in_doc_comments=true --config wrap_comments=true
    cargo clippy -- -D warnings
fi
RUSTDOCFLAGS="-Dwarnings" cargo doc
