[package]
name = "secops_simulator"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]

rdkafka = { version = "0.29.0", features = ["cmake-build"] }
futures = "0.3.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.2.2"
rand = "0.8.5"
mockd = { version = "0.4.1", features = ["datetime"] }
circular-queue = "0.2.6"
