name: Benchmark DBSP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  CI_MACHINE_TYPE: "skylake-2x"
  FORCE_COLOR: 1

jobs:
  benchmark:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: [self-hosted, skylake40, benchmark-machine]
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.7.17

      - name: MUIX license
        run: echo "NEXT_PUBLIC_MUIX_PRO_KEY=${muix_license}" > web-console/.env && cat web-console/.env
        env:
          muix_license: ${{ secrets.muix_license }}

      - name: Earthly version
        run: earthly --version

      - name: Run Benchmarks
        run: earthly --verbose -P +benchmark

      - name: Publish results
        run: bash ./scripts/bench-publish.bash

      # Find comment with benchmark info if it exists
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ github.event.client_payload.github.payload.issue.number != '' }}
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body-file: nexmark_comment.txt
          edit-mode: replace
