name: Benchmark Flink

on:
  schedule:
    # Run every month on the first day
    - cron:  '0 0 1 * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTUP_MAX_RETRIES: 10
  CI_MACHINE_TYPE: "skylake-2x"
  FORCE_COLOR: 1

jobs:
  benchmark:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: [ self-hosted, skylake40, benchmark-machine ]
    steps:
      - uses: actions/checkout@v3

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8.14

      - name: Earthly version
        run: earthly --version

      - name: Fetch previous results
        run: bash ./scripts/clone-gh-pages.bash

      - name: Refresh Flink Benchmark
        run: bash ./benchmark/flink/refresh-flink-benchmark.sh

      - name: Publish Flink Results
        run: bash ./benchmark/flink/publish-flink.sh